<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class Geolocations extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('departaments')->insert([
            ['name' => 'Antioquia', 'code' => 5],
            ['name' => 'Atlantico', 'code' => 8],
            ['name' => 'D. C. Santa Fe de Bogotá', 'code' => 11],
            ['name' => 'Bolivar', 'code' => 13],
            ['name' => 'Boyaca', 'code' => 15],
            ['name' => 'Caldas', 'code' => 17],
            ['name' => 'Caqueta', 'code' => 18],
            ['name' => 'Cauca', 'code' => 19],
            ['name' => 'Cesar', 'code' => 20],
            ['name' => 'Cordova', 'code' => 23],
            ['name' => 'Cundinamarca', 'code' => 25],
            ['name' => 'Choco', 'code' => 27],
            ['name' => 'Huila', 'code' => 41],
            ['name' => 'La Guajira', 'code' => 44],
            ['name' => 'Magdalena', 'code' => 47],
            ['name' => 'Meta', 'code' => 50],
            ['name' => 'Nariño', 'code' => 52],
            ['name' => 'Norte de Santander', 'code' => 54],
            ['name' => 'Quindio', 'code' => 63],
            ['name' => 'Risaralda', 'code' => 66],
            ['name' => 'Santander', 'code' => 68],
            ['name' => 'Sucre', 'code' => 70],
            ['name' => 'Tolima', 'code' => 73],
            ['name' => 'Valle', 'code' => 76],
            ['name' => 'Arauca', 'code' => 81],
            ['name' => 'Casanare', 'code' => 85],
            ['name' => 'Putumayo', 'code' => 86],
            ['name' => 'San Andres', 'code' => 88],
            ['name' => 'Amazonas', 'code' => 91],
            ['name' => 'Guainia', 'code' => 94],
            ['name' => 'Guaviare', 'code' => 95],
            ['name' => 'Vaupes', 'code' => 97],
            ['name' => 'Vichada', 'code' => 99],
        ]);

        DB::table('municipalities')->insert([
            ['departament_id' => 1, 'code' => 1, 'name' => 'MEDELLIN'],
            ['departament_id' => 1, 'code' => 2, 'name' => 'ABEJORRAL'],
            ['departament_id' => 1, 'code' => 4, 'name' => 'ABRIAQUI'],
            ['departament_id' => 1, 'code' => 21, 'name' => 'ALEJANDRIA'],
            ['departament_id' => 1, 'code' => 30, 'name' => 'AMAGA'],
            ['departament_id' => 1, 'code' => 31, 'name' => 'AMALFI'],
            ['departament_id' => 1, 'code' => 34, 'name' => 'ANDES'],
            ['departament_id' => 1, 'code' => 36, 'name' => 'ANGELOPOLIS'],
            ['departament_id' => 1, 'code' => 38, 'name' => 'ANGOSTURA'],
            ['departament_id' => 1, 'code' => 40, 'name' => 'ANORI'],
            ['departament_id' => 1, 'code' => 42, 'name' => 'ANTIOQUIA'],
            ['departament_id' => 1, 'code' => 44, 'name' => 'ANZA'],
            ['departament_id' => 1, 'code' => 45, 'name' => 'APARTADO'],
            ['departament_id' => 1, 'code' => 51, 'name' => 'ARBOLETES'],
            ['departament_id' => 1, 'code' => 55, 'name' => 'ARGELIA'],
            ['departament_id' => 1, 'code' => 59, 'name' => 'ARMENIA'],
            ['departament_id' => 1, 'code' => 79, 'name' => 'BARBOSA'],
            ['departament_id' => 1, 'code' => 86, 'name' => 'BELMIRA'],
            ['departament_id' => 1, 'code' => 88, 'name' => 'BELLO'],
            ['departament_id' => 1, 'code' => 91, 'name' => 'BETANIA'],
            ['departament_id' => 1, 'code' => 93, 'name' => 'BETULIA'],
            ['departament_id' => 1, 'code' => 101, 'name' => 'BOLIVAR'],
            ['departament_id' => 1, 'code' => 107, 'name' => 'BRICEÑO'],
            ['departament_id' => 1, 'code' => 113, 'name' => 'BURITICA'],
            ['departament_id' => 1, 'code' => 120, 'name' => 'CACERES'],
            ['departament_id' => 1, 'code' => 125, 'name' => 'CAICEDO'],
            ['departament_id' => 1, 'code' => 129, 'name' => 'CALDAS'],
            ['departament_id' => 1, 'code' => 134, 'name' => 'CAMPAMENTO'],
            ['departament_id' => 1, 'code' => 138, 'name' => 'CAÑASGORDAS'],
            ['departament_id' => 1, 'code' => 142, 'name' => 'CARACOLI'],
            ['departament_id' => 1, 'code' => 145, 'name' => 'CARAMANTA'],
            ['departament_id' => 1, 'code' => 147, 'name' => 'CAREPA'],
            ['departament_id' => 1, 'code' => 148, 'name' => 'CARMEN DE VIBORAL'],
            ['departament_id' => 1, 'code' => 150, 'name' => 'CAROLINA'],
            ['departament_id' => 1, 'code' => 154, 'name' => 'CAUCASIA'],
            ['departament_id' => 1, 'code' => 172, 'name' => 'CHIGORODO'],
            ['departament_id' => 1, 'code' => 190, 'name' => 'CISNEROS'],
            ['departament_id' => 1, 'code' => 197, 'name' => 'COCORNA'],
            ['departament_id' => 1, 'code' => 206, 'name' => 'CONCEPCION'],
            ['departament_id' => 1, 'code' => 209, 'name' => 'CONCORDIA'],
            ['departament_id' => 1, 'code' => 212, 'name' => 'COPACABANA'],
            ['departament_id' => 1, 'code' => 234, 'name' => 'DABEIBA'],
            ['departament_id' => 1, 'code' => 237, 'name' => 'DON MATIAS'],
            ['departament_id' => 1, 'code' => 240, 'name' => 'EBEJICO'],
            ['departament_id' => 1, 'code' => 250, 'name' => 'EL BAGRE'],
            ['departament_id' => 1, 'code' => 264, 'name' => 'ENTRERRIOS'],
            ['departament_id' => 1, 'code' => 266, 'name' => 'ENVIGADO'],
            ['departament_id' => 1, 'code' => 282, 'name' => 'FREDONIA'],
            ['departament_id' => 1, 'code' => 284, 'name' => 'FRONTINO'],
            ['departament_id' => 1, 'code' => 306, 'name' => 'GIRALDO'],
            ['departament_id' => 1, 'code' => 308, 'name' => 'GIRARDOTA'],
            ['departament_id' => 1, 'code' => 310, 'name' => 'GOMEZ PLATA'],
            ['departament_id' => 1, 'code' => 313, 'name' => 'GRANADA'],
            ['departament_id' => 1, 'code' => 315, 'name' => 'GUADALUPE'],
            ['departament_id' => 1, 'code' => 318, 'name' => 'GUARNE'],
            ['departament_id' => 1, 'code' => 321, 'name' => 'GUATAPE'],
            ['departament_id' => 1, 'code' => 347, 'name' => 'HELICONIA'],
            ['departament_id' => 1, 'code' => 353, 'name' => 'HISPANIA'],
            ['departament_id' => 1, 'code' => 360, 'name' => 'ITAGUI'],
            ['departament_id' => 1, 'code' => 361, 'name' => 'ITUANGO'],
            ['departament_id' => 1, 'code' => 364, 'name' => 'JARDIN'],
            ['departament_id' => 1, 'code' => 368, 'name' => 'JERICO'],
            ['departament_id' => 1, 'code' => 376, 'name' => 'LA CEJA'],
            ['departament_id' => 1, 'code' => 380, 'name' => 'LA ESTRELLA'],
            ['departament_id' => 1, 'code' => 390, 'name' => 'LA PINTADA'],
            ['departament_id' => 1, 'code' => 400, 'name' => 'LA UNION'],
            ['departament_id' => 1, 'code' => 411, 'name' => 'LIBORINA'],
            ['departament_id' => 1, 'code' => 425, 'name' => 'MACEO'],
            ['departament_id' => 1, 'code' => 440, 'name' => 'MARINILLA'],
            ['departament_id' => 1, 'code' => 467, 'name' => 'MONTEBELLO'],
            ['departament_id' => 1, 'code' => 475, 'name' => 'MURINDO'],
            ['departament_id' => 1, 'code' => 480, 'name' => 'MUTATA'],
            ['departament_id' => 1, 'code' => 483, 'name' => 'NARIÑO'],
            ['departament_id' => 1, 'code' => 490, 'name' => 'NECOCLI'],
            ['departament_id' => 1, 'code' => 495, 'name' => 'NECHI'],
            ['departament_id' => 1, 'code' => 501, 'name' => 'OLAYA'],
            ['departament_id' => 1, 'code' => 541, 'name' => 'PEÑOL'],
            ['departament_id' => 1, 'code' => 543, 'name' => 'PEQUE'],
            ['departament_id' => 1, 'code' => 576, 'name' => 'PUEBLORRICO'],
            ['departament_id' => 1, 'code' => 579, 'name' => 'PUERTO BERRIO'],
            ['departament_id' => 1, 'code' => 585, 'name' => 'PUERTO NARE (LA MAGDALENA)'],
            ['departament_id' => 1, 'code' => 591, 'name' => 'PUERTO TRIUNFO'],
            ['departament_id' => 1, 'code' => 604, 'name' => 'REMEDIOS'],
            ['departament_id' => 1, 'code' => 607, 'name' => 'RETIRO'],
            ['departament_id' => 1, 'code' => 615, 'name' => 'RIONEGRO'],
            ['departament_id' => 1, 'code' => 628, 'name' => 'SABANALARGA'],
            ['departament_id' => 1, 'code' => 631, 'name' => 'SABANETA'],
            ['departament_id' => 1, 'code' => 642, 'name' => 'SALGAR'],
            ['departament_id' => 1, 'code' => 647, 'name' => 'SAN ANDRES'],
            ['departament_id' => 1, 'code' => 649, 'name' => 'SAN CARLOS'],
            ['departament_id' => 1, 'code' => 652, 'name' => 'SAN FRANCISCO'],
            ['departament_id' => 1, 'code' => 656, 'name' => 'SAN JERONIMO'],
            ['departament_id' => 1, 'code' => 658, 'name' => 'SAN JOSE DE LA MONTAÑA'],
            ['departament_id' => 1, 'code' => 659, 'name' => 'SAN JUAN DE URABA'],
            ['departament_id' => 1, 'code' => 660, 'name' => 'SAN LUIS'],
            ['departament_id' => 1, 'code' => 664, 'name' => 'SAN PEDRO'],
            ['departament_id' => 1, 'code' => 665, 'name' => 'SAN PEDRO DE URABA'],
            ['departament_id' => 1, 'code' => 667, 'name' => 'SAN RAFAEL'],
            ['departament_id' => 1, 'code' => 670, 'name' => 'SAN ROQUE'],
            ['departament_id' => 1, 'code' => 674, 'name' => 'SAN VICENTE'],
            ['departament_id' => 1, 'code' => 679, 'name' => 'SANTA BARBARA'],
            ['departament_id' => 1, 'code' => 686, 'name' => 'SANTA ROSA DE OSOS'],
            ['departament_id' => 1, 'code' => 690, 'name' => 'SANTO DOMINGO'],
            ['departament_id' => 1, 'code' => 697, 'name' => 'SANTUARIO'],
            ['departament_id' => 1, 'code' => 736, 'name' => 'SEGOVIA'],
            ['departament_id' => 1, 'code' => 756, 'name' => 'SONSON'],
            ['departament_id' => 1, 'code' => 761, 'name' => 'SOPETRAN'],
            ['departament_id' => 1, 'code' => 789, 'name' => 'TAMESIS'],
            ['departament_id' => 1, 'code' => 790, 'name' => 'TARAZA'],
            ['departament_id' => 1, 'code' => 792, 'name' => 'TARSO'],
            ['departament_id' => 1, 'code' => 809, 'name' => 'TITIRIBI'],
            ['departament_id' => 1, 'code' => 819, 'name' => 'TOLEDO'],
            ['departament_id' => 1, 'code' => 837, 'name' => 'TURBO'],
            ['departament_id' => 1, 'code' => 842, 'name' => 'URAMITA'],
            ['departament_id' => 1, 'code' => 847, 'name' => 'URRAO'],
            ['departament_id' => 1, 'code' => 854, 'name' => 'VALDIVIA'],
            ['departament_id' => 1, 'code' => 856, 'name' => 'VALPARAISO'],
            ['departament_id' => 1, 'code' => 858, 'name' => 'VEGACHI'],
            ['departament_id' => 1, 'code' => 861, 'name' => 'VENECIA'],
            ['departament_id' => 1, 'code' => 873, 'name' => 'VIGIA DEL FUERTE'],
            ['departament_id' => 1, 'code' => 885, 'name' => 'YALI'],
            ['departament_id' => 1, 'code' => 887, 'name' => 'YARUMAL'],
            ['departament_id' => 1, 'code' => 890, 'name' => 'YOLOMBO'],
            ['departament_id' => 1, 'code' => 893, 'name' => 'YONDO'],
            ['departament_id' => 1, 'code' => 895, 'name' => 'ZARAGOZA'],
            ['departament_id' => 2, 'code' => 1, 'name' => 'BARRANQUILLA (DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA)'],
            ['departament_id' => 2, 'code' => 78, 'name' => 'BARANOA'],
            ['departament_id' => 2, 'code' => 137, 'name' => 'CAMPO DE LA CRUZ'],
            ['departament_id' => 2, 'code' => 141, 'name' => 'CANDELARIA'],
            ['departament_id' => 2, 'code' => 296, 'name' => 'GALAPA'],
            ['departament_id' => 2, 'code' => 372, 'name' => 'JUAN DE ACOSTA'],
            ['departament_id' => 2, 'code' => 421, 'name' => 'LURUACO'],
            ['departament_id' => 2, 'code' => 433, 'name' => 'MALAMBO'],
            ['departament_id' => 2, 'code' => 436, 'name' => 'MANATI'],
            ['departament_id' => 2, 'code' => 520, 'name' => 'PALMAR DE VARELA'],
            ['departament_id' => 2, 'code' => 549, 'name' => 'PIOJO'],
            ['departament_id' => 2, 'code' => 558, 'name' => 'POLO NUEVO'],
            ['departament_id' => 2, 'code' => 560, 'name' => 'PONEDERA'],
            ['departament_id' => 2, 'code' => 573, 'name' => 'PUERTO COLOMBIA'],
            ['departament_id' => 2, 'code' => 606, 'name' => 'REPELON'],
            ['departament_id' => 2, 'code' => 634, 'name' => 'SABANAGRANDE'],
            ['departament_id' => 2, 'code' => 638, 'name' => 'SABANALARGA'],
            ['departament_id' => 2, 'code' => 675, 'name' => 'SANTA LUCIA'],
            ['departament_id' => 2, 'code' => 685, 'name' => 'SANTO TOMAS'],
            ['departament_id' => 2, 'code' => 758, 'name' => 'SOLEDAD'],
            ['departament_id' => 2, 'code' => 770, 'name' => 'SUAN'],
            ['departament_id' => 2, 'code' => 832, 'name' => 'TUBARA'],
            ['departament_id' => 2, 'code' => 849, 'name' => 'USIACURI'],
            ['departament_id' => 3, 'code' => 1, 'name' => 'Santa Fe de Bogotá'],
            ['departament_id' => 3, 'code' => 1, 'name' => 'USAQUEN'],
            ['departament_id' => 3, 'code' => 2, 'name' => 'CHAPINERO'],
            ['departament_id' => 3, 'code' => 3, 'name' => 'SANTA FE'],
            ['departament_id' => 3, 'code' => 4, 'name' => 'SAN CRISTOBAL'],
            ['departament_id' => 3, 'code' => 5, 'name' => 'USME'],
            ['departament_id' => 3, 'code' => 6, 'name' => 'TUNJUELITO'],
            ['departament_id' => 3, 'code' => 7, 'name' => 'BOSA'],
            ['departament_id' => 3, 'code' => 8, 'name' => 'KENNEDY'],
            ['departament_id' => 3, 'code' => 9, 'name' => 'FONTIBON'],
            ['departament_id' => 3, 'code' => 10, 'name' => 'ENGATIVA'],
            ['departament_id' => 3, 'code' => 11, 'name' => 'SUBA'],
            ['departament_id' => 3, 'code' => 12, 'name' => 'BARRIOS UNIDOS'],
            ['departament_id' => 3, 'code' => 13, 'name' => 'TEUSAQUILLO'],
            ['departament_id' => 3, 'code' => 14, 'name' => 'MARTIRES'],
            ['departament_id' => 3, 'code' => 15, 'name' => 'ANTONIO NARIÑO'],
            ['departament_id' => 3, 'code' => 16, 'name' => 'PUENTE ARANDA'],
            ['departament_id' => 3, 'code' => 17, 'name' => 'CANDELARIA'],
            ['departament_id' => 3, 'code' => 18, 'name' => 'RAFAEL URIBE'],
            ['departament_id' => 3, 'code' => 19, 'name' => 'CIUDAD BOLIVAR'],
            ['departament_id' => 3, 'code' => 20, 'name' => 'SUMAPAZ'],
            ['departament_id' => 4, 'code' => 1, 'name' => 'CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA)'],
            ['departament_id' => 4, 'code' => 6, 'name' => 'ACHI'],
            ['departament_id' => 4, 'code' => 30, 'name' => 'ALTOS DEL ROSARIO'],
            ['departament_id' => 4, 'code' => 42, 'name' => 'ARENAL'],
            ['departament_id' => 4, 'code' => 52, 'name' => 'ARJONA'],
            ['departament_id' => 4, 'code' => 62, 'name' => 'ARROYOHONDO'],
            ['departament_id' => 4, 'code' => 74, 'name' => 'BARRANCO DE LOBA'],
            ['departament_id' => 4, 'code' => 140, 'name' => 'CALAMAR'],
            ['departament_id' => 4, 'code' => 160, 'name' => 'CANTAGALLO'],
            ['departament_id' => 4, 'code' => 188, 'name' => 'CICUCO'],
            ['departament_id' => 4, 'code' => 212, 'name' => 'CORDOBA'],
            ['departament_id' => 4, 'code' => 222, 'name' => 'CLEMENCIA'],
            ['departament_id' => 4, 'code' => 244, 'name' => 'EL CARMEN DE BOLIVAR'],
            ['departament_id' => 4, 'code' => 248, 'name' => 'EL GUAMO'],
            ['departament_id' => 4, 'code' => 268, 'name' => 'EL PEÑON'],
            ['departament_id' => 4, 'code' => 300, 'name' => 'HATILLO DE LOBA'],
            ['departament_id' => 4, 'code' => 430, 'name' => 'MAGANGUE'],
            ['departament_id' => 4, 'code' => 433, 'name' => 'MAHATES'],
            ['departament_id' => 4, 'code' => 440, 'name' => 'MARGARITA'],
            ['departament_id' => 4, 'code' => 442, 'name' => 'MARIA LA BAJA'],
            ['departament_id' => 4, 'code' => 458, 'name' => 'MONTECRISTO'],
            ['departament_id' => 4, 'code' => 468, 'name' => 'MOMPOS'],
            ['departament_id' => 4, 'code' => 473, 'name' => 'MORALES'],
            ['departament_id' => 4, 'code' => 549, 'name' => 'PINILLOS'],
            ['departament_id' => 4, 'code' => 580, 'name' => 'REGIDOR'],
            ['departament_id' => 4, 'code' => 600, 'name' => 'RIO VIEJO'],
            ['departament_id' => 4, 'code' => 620, 'name' => 'SAN CRISTOBAL'],
            ['departament_id' => 4, 'code' => 647, 'name' => 'SAN ESTANISLAO'],
            ['departament_id' => 4, 'code' => 650, 'name' => 'SAN FERNANDO'],
            ['departament_id' => 4, 'code' => 654, 'name' => 'SAN JACINTO'],
            ['departament_id' => 4, 'code' => 655, 'name' => 'SAN JACINTO DEL CAUCA'],
            ['departament_id' => 4, 'code' => 657, 'name' => 'SAN JUAN NEPOMUCENO'],
            ['departament_id' => 4, 'code' => 667, 'name' => 'SAN MARTIN DE LOBA'],
            ['departament_id' => 4, 'code' => 670, 'name' => 'SAN PABLO'],
            ['departament_id' => 4, 'code' => 673, 'name' => 'SANTA CATALINA'],
            ['departament_id' => 4, 'code' => 683, 'name' => 'SANTA ROSA'],
            ['departament_id' => 4, 'code' => 688, 'name' => 'SANTA ROSA DEL SUR'],
            ['departament_id' => 4, 'code' => 744, 'name' => 'SIMITI'],
            ['departament_id' => 4, 'code' => 760, 'name' => 'SOPLAVIENTO'],
            ['departament_id' => 4, 'code' => 780, 'name' => 'TALAIGUA NUEVO'],
            ['departament_id' => 4, 'code' => 810, 'name' => 'TIQUISIO (PUERTO RICO)'],
            ['departament_id' => 4, 'code' => 836, 'name' => 'TURBACO'],
            ['departament_id' => 4, 'code' => 838, 'name' => 'TURBANA'],
            ['departament_id' => 4, 'code' => 873, 'name' => 'VILLANUEVA'],
            ['departament_id' => 4, 'code' => 894, 'name' => 'ZAMBRANO'],
            ['departament_id' => 5, 'code' => 1, 'name' => 'TUNJA'],
            ['departament_id' => 5, 'code' => 22, 'name' => 'ALMEIDA'],
            ['departament_id' => 5, 'code' => 47, 'name' => 'AQUITANIA'],
            ['departament_id' => 5, 'code' => 51, 'name' => 'ARCABUCO'],
            ['departament_id' => 5, 'code' => 87, 'name' => 'BELEN'],
            ['departament_id' => 5, 'code' => 90, 'name' => 'BERBEO'],
            ['departament_id' => 5, 'code' => 92, 'name' => 'BETEITIVA'],
            ['departament_id' => 5, 'code' => 97, 'name' => 'BOAVITA'],
            ['departament_id' => 5, 'code' => 104, 'name' => 'BOYACA'],
            ['departament_id' => 5, 'code' => 106, 'name' => 'BRICEÑO'],
            ['departament_id' => 5, 'code' => 109, 'name' => 'BUENAVISTA'],
            ['departament_id' => 5, 'code' => 114, 'name' => 'BUSBANZA'],
            ['departament_id' => 5, 'code' => 131, 'name' => 'CALDAS'],
            ['departament_id' => 5, 'code' => 135, 'name' => 'CAMPOHERMOSO'],
            ['departament_id' => 5, 'code' => 162, 'name' => 'CERINZA'],
            ['departament_id' => 5, 'code' => 172, 'name' => 'CHINAVITA'],
            ['departament_id' => 5, 'code' => 176, 'name' => 'CHIQUINQUIRA'],
            ['departament_id' => 5, 'code' => 180, 'name' => 'CHISCAS'],
            ['departament_id' => 5, 'code' => 183, 'name' => 'CHITA'],
            ['departament_id' => 5, 'code' => 185, 'name' => 'CHITARAQUE'],
            ['departament_id' => 5, 'code' => 187, 'name' => 'CHIVATA'],
            ['departament_id' => 5, 'code' => 189, 'name' => 'CIENEGA'],
            ['departament_id' => 5, 'code' => 204, 'name' => 'COMBITA'],
            ['departament_id' => 5, 'code' => 212, 'name' => 'COPER'],
            ['departament_id' => 5, 'code' => 215, 'name' => 'CORRALES'],
            ['departament_id' => 5, 'code' => 218, 'name' => 'COVARACHIA'],
            ['departament_id' => 5, 'code' => 223, 'name' => 'CUBARA'],
            ['departament_id' => 5, 'code' => 224, 'name' => 'CUCAITA'],
            ['departament_id' => 5, 'code' => 226, 'name' => 'CUITIVA'],
            ['departament_id' => 5, 'code' => 232, 'name' => 'CHIQUIZA'],
            ['departament_id' => 5, 'code' => 236, 'name' => 'CHIVOR'],
            ['departament_id' => 5, 'code' => 238, 'name' => 'DUITAMA'],
            ['departament_id' => 5, 'code' => 244, 'name' => 'EL COCUY'],
            ['departament_id' => 5, 'code' => 248, 'name' => 'EL ESPINO'],
            ['departament_id' => 5, 'code' => 272, 'name' => 'FIRAVITOBA'],
            ['departament_id' => 5, 'code' => 276, 'name' => 'FLORESTA'],
            ['departament_id' => 5, 'code' => 293, 'name' => 'GACHANTIVA'],
            ['departament_id' => 5, 'code' => 296, 'name' => 'GAMEZA'],
            ['departament_id' => 5, 'code' => 299, 'name' => 'GARAGOA'],
            ['departament_id' => 5, 'code' => 317, 'name' => 'GUACAMAYAS'],
            ['departament_id' => 5, 'code' => 322, 'name' => 'GUATEQUE'],
            ['departament_id' => 5, 'code' => 325, 'name' => 'GUAYATA'],
            ['departament_id' => 5, 'code' => 332, 'name' => 'GUICAN'],
            ['departament_id' => 5, 'code' => 362, 'name' => 'IZA'],
            ['departament_id' => 5, 'code' => 367, 'name' => 'JENESANO'],
            ['departament_id' => 5, 'code' => 368, 'name' => 'JERICO'],
            ['departament_id' => 5, 'code' => 377, 'name' => 'LABRANZAGRANDE'],
            ['departament_id' => 5, 'code' => 380, 'name' => 'LA CAPILLA'],
            ['departament_id' => 5, 'code' => 401, 'name' => 'LA VICTORIA'],
            ['departament_id' => 5, 'code' => 403, 'name' => 'LA UVITA'],
            ['departament_id' => 5, 'code' => 407, 'name' => 'VILLA DE LEIVA'],
            ['departament_id' => 5, 'code' => 425, 'name' => 'MACANAL'],
            ['departament_id' => 5, 'code' => 442, 'name' => 'MARIPI'],
            ['departament_id' => 5, 'code' => 455, 'name' => 'MIRAFLORES'],
            ['departament_id' => 5, 'code' => 464, 'name' => 'MONGUA'],
            ['departament_id' => 5, 'code' => 466, 'name' => 'MONGUI'],
            ['departament_id' => 5, 'code' => 469, 'name' => 'MONIQUIRA'],
            ['departament_id' => 5, 'code' => 476, 'name' => 'MOTAVITA'],
            ['departament_id' => 5, 'code' => 480, 'name' => 'MUZO'],
            ['departament_id' => 5, 'code' => 491, 'name' => 'NOBSA'],
            ['departament_id' => 5, 'code' => 494, 'name' => 'NUEVO COLON'],
            ['departament_id' => 5, 'code' => 500, 'name' => 'OICATA'],
            ['departament_id' => 5, 'code' => 507, 'name' => 'OTANCHE'],
            ['departament_id' => 5, 'code' => 511, 'name' => 'PACHAVITA'],
            ['departament_id' => 5, 'code' => 514, 'name' => 'PAEZ'],
            ['departament_id' => 5, 'code' => 516, 'name' => 'PAIPA'],
            ['departament_id' => 5, 'code' => 518, 'name' => 'PAJARITO'],
            ['departament_id' => 5, 'code' => 522, 'name' => 'PANQUEBA'],
            ['departament_id' => 5, 'code' => 531, 'name' => 'PAUNA'],
            ['departament_id' => 5, 'code' => 533, 'name' => 'PAYA'],
            ['departament_id' => 5, 'code' => 537, 'name' => 'PAZ DEL RIO'],
            ['departament_id' => 5, 'code' => 542, 'name' => 'PESCA'],
            ['departament_id' => 5, 'code' => 550, 'name' => 'PISBA'],
            ['departament_id' => 5, 'code' => 572, 'name' => 'PUERTO BOYACA'],
            ['departament_id' => 5, 'code' => 580, 'name' => 'QUIPAMA'],
            ['departament_id' => 5, 'code' => 599, 'name' => 'RAMIRIQUI'],
            ['departament_id' => 5, 'code' => 600, 'name' => 'RAQUIRA'],
            ['departament_id' => 5, 'code' => 621, 'name' => 'RONDON'],
            ['departament_id' => 5, 'code' => 632, 'name' => 'SABOYA'],
            ['departament_id' => 5, 'code' => 638, 'name' => 'SACHICA'],
            ['departament_id' => 5, 'code' => 646, 'name' => 'SAMACA'],
            ['departament_id' => 5, 'code' => 660, 'name' => 'SAN EDUARDO'],
            ['departament_id' => 5, 'code' => 664, 'name' => 'SAN JOSE DE PARE'],
            ['departament_id' => 5, 'code' => 667, 'name' => 'SAN LUIS DE GACENO'],
            ['departament_id' => 5, 'code' => 673, 'name' => 'SAN MATEO'],
            ['departament_id' => 5, 'code' => 676, 'name' => 'SAN MIGUEL DE SEMA'],
            ['departament_id' => 5, 'code' => 681, 'name' => 'SAN PABLO DE BORBUR'],
            ['departament_id' => 5, 'code' => 686, 'name' => 'SANTANA'],
            ['departament_id' => 5, 'code' => 690, 'name' => 'SANTA MARIA'],
            ['departament_id' => 5, 'code' => 693, 'name' => 'SANTA ROSA DE VITERBO'],
            ['departament_id' => 5, 'code' => 696, 'name' => 'SANTA SOFIA'],
            ['departament_id' => 5, 'code' => 720, 'name' => 'SATIVANORTE'],
            ['departament_id' => 5, 'code' => 723, 'name' => 'SATIVASUR'],
            ['departament_id' => 5, 'code' => 740, 'name' => 'SIACHOQUE'],
            ['departament_id' => 5, 'code' => 753, 'name' => 'SOATA'],
            ['departament_id' => 5, 'code' => 755, 'name' => 'SOCOTA'],
            ['departament_id' => 5, 'code' => 757, 'name' => 'SOCHA'],
            ['departament_id' => 5, 'code' => 759, 'name' => 'SOGAMOSO'],
            ['departament_id' => 5, 'code' => 761, 'name' => 'SOMONDOCO'],
            ['departament_id' => 5, 'code' => 762, 'name' => 'SORA'],
            ['departament_id' => 5, 'code' => 763, 'name' => 'SOTAQUIRA'],
            ['departament_id' => 5, 'code' => 764, 'name' => 'SORACA'],
            ['departament_id' => 5, 'code' => 774, 'name' => 'SUSACON'],
            ['departament_id' => 5, 'code' => 776, 'name' => 'SUTAMARCHAN'],
            ['departament_id' => 5, 'code' => 778, 'name' => 'SUTATENZA'],
            ['departament_id' => 5, 'code' => 790, 'name' => 'TASCO'],
            ['departament_id' => 5, 'code' => 798, 'name' => 'TENZA'],
            ['departament_id' => 5, 'code' => 804, 'name' => 'TIBANA'],
            ['departament_id' => 5, 'code' => 806, 'name' => 'TIBASOSA'],
            ['departament_id' => 5, 'code' => 808, 'name' => 'TINJACA'],
            ['departament_id' => 5, 'code' => 810, 'name' => 'TIPACOQUE'],
            ['departament_id' => 5, 'code' => 814, 'name' => 'TOCA'],
            ['departament_id' => 5, 'code' => 816, 'name' => 'TOGUI'],
            ['departament_id' => 5, 'code' => 820, 'name' => 'TOPAGA'],
            ['departament_id' => 5, 'code' => 822, 'name' => 'TOTA'],
            ['departament_id' => 5, 'code' => 832, 'name' => 'TUNUNGUA'],
            ['departament_id' => 5, 'code' => 835, 'name' => 'TURMEQUE'],
            ['departament_id' => 5, 'code' => 837, 'name' => 'TUTA'],
            ['departament_id' => 5, 'code' => 839, 'name' => 'TUTASA'],
            ['departament_id' => 5, 'code' => 842, 'name' => 'UMBITA'],
            ['departament_id' => 5, 'code' => 861, 'name' => 'VENTAQUEMADA'],
            ['departament_id' => 5, 'code' => 879, 'name' => 'VIRACACHA'],
            ['departament_id' => 5, 'code' => 897, 'name' => 'ZETAQUIRA'],
            ['departament_id' => 6, 'code' => 1, 'name' => 'MANIZALES'],
            ['departament_id' => 6, 'code' => 13, 'name' => 'AGUADAS'],
            ['departament_id' => 6, 'code' => 42, 'name' => 'ANSERMA'],
            ['departament_id' => 6, 'code' => 50, 'name' => 'ARANZAZU'],
            ['departament_id' => 6, 'code' => 88, 'name' => 'BELALCAZAR'],
            ['departament_id' => 6, 'code' => 174, 'name' => 'CHINCHINA'],
            ['departament_id' => 6, 'code' => 272, 'name' => 'FILADELFIA'],
            ['departament_id' => 6, 'code' => 380, 'name' => 'LA DORADA'],
            ['departament_id' => 6, 'code' => 388, 'name' => 'LA MERCED'],
            ['departament_id' => 6, 'code' => 433, 'name' => 'MANZANARES'],
            ['departament_id' => 6, 'code' => 442, 'name' => 'MARMATO'],
            ['departament_id' => 6, 'code' => 444, 'name' => 'MARQUETALIA'],
            ['departament_id' => 6, 'code' => 446, 'name' => 'MARULANDA'],
            ['departament_id' => 6, 'code' => 486, 'name' => 'NEIRA'],
            ['departament_id' => 6, 'code' => 495, 'name' => 'NORCASIA'],
            ['departament_id' => 6, 'code' => 513, 'name' => 'PACORA'],
            ['departament_id' => 6, 'code' => 524, 'name' => 'PALESTINA'],
            ['departament_id' => 6, 'code' => 541, 'name' => 'PENSILVANIA'],
            ['departament_id' => 6, 'code' => 614, 'name' => 'RIOSUCIO'],
            ['departament_id' => 6, 'code' => 616, 'name' => 'RISARALDA'],
            ['departament_id' => 6, 'code' => 653, 'name' => 'SALAMINA'],
            ['departament_id' => 6, 'code' => 662, 'name' => 'SAMANA'],
            ['departament_id' => 6, 'code' => 665, 'name' => 'SAN JOSE'],
            ['departament_id' => 6, 'code' => 777, 'name' => 'SUPIA'],
            ['departament_id' => 6, 'code' => 867, 'name' => 'VICTORIA'],
            ['departament_id' => 6, 'code' => 873, 'name' => 'VILLAMARIA'],
            ['departament_id' => 6, 'code' => 877, 'name' => 'VITERBO'],
            ['departament_id' => 7, 'code' => 1, 'name' => 'FLORENCIA'],
            ['departament_id' => 7, 'code' => 29, 'name' => 'ALBANIA'],
            ['departament_id' => 7, 'code' => 94, 'name' => 'BELEN DE LOS ANDAQUIES'],
            ['departament_id' => 7, 'code' => 150, 'name' => 'CARTAGENA DEL CHAIRA'],
            ['departament_id' => 7, 'code' => 205, 'name' => 'CURILLO'],
            ['departament_id' => 7, 'code' => 247, 'name' => 'EL DONCELLO'],
            ['departament_id' => 7, 'code' => 256, 'name' => 'EL PAUJIL'],
            ['departament_id' => 7, 'code' => 410, 'name' => 'LA MONTAÑITA'],
            ['departament_id' => 7, 'code' => 460, 'name' => 'MILAN'],
            ['departament_id' => 7, 'code' => 479, 'name' => 'MORELIA'],
            ['departament_id' => 7, 'code' => 592, 'name' => 'PUERTO RICO'],
            ['departament_id' => 7, 'code' => 610, 'name' => 'SAN JOSE DE FRAGUA'],
            ['departament_id' => 7, 'code' => 753, 'name' => 'SAN VICENTE DEL CAGUAN'],
            ['departament_id' => 7, 'code' => 756, 'name' => 'SOLANO'],
            ['departament_id' => 7, 'code' => 785, 'name' => 'SOLITA'],
            ['departament_id' => 7, 'code' => 860, 'name' => 'VALPARAISO'],
            ['departament_id' => 8, 'code' => 1, 'name' => 'POPAYAN'],
            ['departament_id' => 8, 'code' => 22, 'name' => 'ALMAGUER'],
            ['departament_id' => 8, 'code' => 50, 'name' => 'ARGELIA'],
            ['departament_id' => 8, 'code' => 75, 'name' => 'BALBOA'],
            ['departament_id' => 8, 'code' => 100, 'name' => 'BOLIVAR'],
            ['departament_id' => 8, 'code' => 110, 'name' => 'BUENOS AIRES'],
            ['departament_id' => 8, 'code' => 130, 'name' => 'CAJIBIO'],
            ['departament_id' => 8, 'code' => 137, 'name' => 'CALDONO'],
            ['departament_id' => 8, 'code' => 142, 'name' => 'CALOTO'],
            ['departament_id' => 8, 'code' => 212, 'name' => 'CORINTO'],
            ['departament_id' => 8, 'code' => 256, 'name' => 'EL TAMBO'],
            ['departament_id' => 8, 'code' => 290, 'name' => 'FLORENCIA'],
            ['departament_id' => 8, 'code' => 318, 'name' => 'GUAPI'],
            ['departament_id' => 8, 'code' => 355, 'name' => 'INZA'],
            ['departament_id' => 8, 'code' => 364, 'name' => 'JAMBALO'],
            ['departament_id' => 8, 'code' => 392, 'name' => 'LA SIERRA'],
            ['departament_id' => 8, 'code' => 397, 'name' => 'LA VEGA'],
            ['departament_id' => 8, 'code' => 418, 'name' => 'LOPEZ (MICAY)'],
            ['departament_id' => 8, 'code' => 450, 'name' => 'MERCADERES'],
            ['departament_id' => 8, 'code' => 455, 'name' => 'MIRANDA'],
            ['departament_id' => 8, 'code' => 473, 'name' => 'MORALES'],
            ['departament_id' => 8, 'code' => 513, 'name' => 'PADILLA'],
            ['departament_id' => 8, 'code' => 517, 'name' => 'PAEZ (BELALCAZAR)'],
            ['departament_id' => 8, 'code' => 532, 'name' => 'PATIA (EL BORDO)'],
            ['departament_id' => 8, 'code' => 533, 'name' => 'PIAMONTE'],
            ['departament_id' => 8, 'code' => 548, 'name' => 'PIENDAMO'],
            ['departament_id' => 8, 'code' => 573, 'name' => 'PUERTO TEJADA'],
            ['departament_id' => 8, 'code' => 585, 'name' => 'PURACE (COCONUCO)'],
            ['departament_id' => 8, 'code' => 622, 'name' => 'ROSAS'],
            ['departament_id' => 8, 'code' => 693, 'name' => 'SAN SEBASTIAN'],
            ['departament_id' => 8, 'code' => 698, 'name' => 'SANTANDER DE QUILICHAO'],
            ['departament_id' => 8, 'code' => 701, 'name' => 'SANTA ROSA'],
            ['departament_id' => 8, 'code' => 743, 'name' => 'SILVIA'],
            ['departament_id' => 8, 'code' => 760, 'name' => 'SOTARA (PAISPAMBA)'],
            ['departament_id' => 8, 'code' => 780, 'name' => 'SUAREZ'],
            ['departament_id' => 8, 'code' => 807, 'name' => 'TIMBIO'],
            ['departament_id' => 8, 'code' => 809, 'name' => 'TIMBIQUI'],
            ['departament_id' => 8, 'code' => 821, 'name' => 'TORIBIO'],
            ['departament_id' => 8, 'code' => 824, 'name' => 'TOTORO'],
            ['departament_id' => 8, 'code' => 845, 'name' => 'VILLARICA'],
            ['departament_id' => 9, 'code' => 1, 'name' => 'VALLEDUPAR'],
            ['departament_id' => 9, 'code' => 11, 'name' => 'AGUACHICA'],
            ['departament_id' => 9, 'code' => 13, 'name' => 'AGUSTIN CODAZZI'],
            ['departament_id' => 9, 'code' => 32, 'name' => 'ASTREA'],
            ['departament_id' => 9, 'code' => 45, 'name' => 'BECERRIL'],
            ['departament_id' => 9, 'code' => 60, 'name' => 'BOSCONIA'],
            ['departament_id' => 9, 'code' => 175, 'name' => 'CHIMICHAGUA'],
            ['departament_id' => 9, 'code' => 178, 'name' => 'CHIRIGUANA'],
            ['departament_id' => 9, 'code' => 228, 'name' => 'CURUMANI'],
            ['departament_id' => 9, 'code' => 238, 'name' => 'EL COPEY'],
            ['departament_id' => 9, 'code' => 250, 'name' => 'EL PASO'],
            ['departament_id' => 9, 'code' => 295, 'name' => 'GAMARRA'],
            ['departament_id' => 9, 'code' => 310, 'name' => 'GONZALEZ'],
            ['departament_id' => 9, 'code' => 383, 'name' => 'LA GLORIA'],
            ['departament_id' => 9, 'code' => 400, 'name' => 'LA JAGUA IBIRICO'],
            ['departament_id' => 9, 'code' => 443, 'name' => 'MANAURE (BALCON DEL CESAR)'],
            ['departament_id' => 9, 'code' => 517, 'name' => 'PAILITAS'],
            ['departament_id' => 9, 'code' => 550, 'name' => 'PELAYA'],
            ['departament_id' => 9, 'code' => 570, 'name' => 'PUEBLO BELLO'],
            ['departament_id' => 9, 'code' => 614, 'name' => 'RIO DE ORO'],
            ['departament_id' => 9, 'code' => 621, 'name' => 'LA PAZ (ROBLES)'],
            ['departament_id' => 9, 'code' => 710, 'name' => 'SAN ALBERTO'],
            ['departament_id' => 9, 'code' => 750, 'name' => 'SAN DIEGO'],
            ['departament_id' => 9, 'code' => 770, 'name' => 'SAN MARTIN'],
            ['departament_id' => 9, 'code' => 787, 'name' => 'TAMALAMEQUE'],
            ['departament_id' => 10, 'code' => 1, 'name' => 'MONTERIA'],
            ['departament_id' => 10, 'code' => 68, 'name' => 'AYAPEL'],
            ['departament_id' => 10, 'code' => 79, 'name' => 'BUENAVISTA'],
            ['departament_id' => 10, 'code' => 90, 'name' => 'CANALETE'],
            ['departament_id' => 10, 'code' => 162, 'name' => 'CERETE'],
            ['departament_id' => 10, 'code' => 168, 'name' => 'CHIMA'],
            ['departament_id' => 10, 'code' => 182, 'name' => 'CHINU'],
            ['departament_id' => 10, 'code' => 189, 'name' => 'CIENAGA DE ORO'],
            ['departament_id' => 10, 'code' => 300, 'name' => 'COTORRA'],
            ['departament_id' => 10, 'code' => 350, 'name' => 'LA APARTADA'],
            ['departament_id' => 10, 'code' => 417, 'name' => 'LORICA'],
            ['departament_id' => 10, 'code' => 419, 'name' => 'LOS CORDOBAS'],
            ['departament_id' => 10, 'code' => 464, 'name' => 'MOMIL'],
            ['departament_id' => 10, 'code' => 466, 'name' => 'MONTELIBANO'],
            ['departament_id' => 10, 'code' => 500, 'name' => 'MOÑITOS'],
            ['departament_id' => 10, 'code' => 555, 'name' => 'PLANETA RICA'],
            ['departament_id' => 10, 'code' => 570, 'name' => 'PUEBLO NUEVO'],
            ['departament_id' => 10, 'code' => 574, 'name' => 'PUERTO ESCONDIDO'],
            ['departament_id' => 10, 'code' => 580, 'name' => 'PUERTO LIBERTADOR'],
            ['departament_id' => 10, 'code' => 586, 'name' => 'PURISIMA'],
            ['departament_id' => 10, 'code' => 660, 'name' => 'SAHAGUN'],
            ['departament_id' => 10, 'code' => 670, 'name' => 'SAN ANDRES SOTAVENTO'],
            ['departament_id' => 10, 'code' => 672, 'name' => 'SAN ANTERO'],
            ['departament_id' => 10, 'code' => 675, 'name' => 'SAN BERNARDO DEL VIENTO'],
            ['departament_id' => 10, 'code' => 678, 'name' => 'SAN CARLOS'],
            ['departament_id' => 10, 'code' => 686, 'name' => 'SAN PELAYO'],
            ['departament_id' => 10, 'code' => 807, 'name' => 'TIERRALTA'],
            ['departament_id' => 10, 'code' => 855, 'name' => 'VALENCIA'],
            ['departament_id' => 11, 'code' => 1, 'name' => 'AGUA DE DIOS'],
            ['departament_id' => 11, 'code' => 19, 'name' => 'ALBAN'],
            ['departament_id' => 11, 'code' => 35, 'name' => 'ANAPOIMA'],
            ['departament_id' => 11, 'code' => 40, 'name' => 'ANOLAIMA'],
            ['departament_id' => 11, 'code' => 53, 'name' => 'ARBELAEZ'],
            ['departament_id' => 11, 'code' => 86, 'name' => 'BELTRAN'],
            ['departament_id' => 11, 'code' => 95, 'name' => 'BITUIMA'],
            ['departament_id' => 11, 'code' => 99, 'name' => 'BOJACA'],
            ['departament_id' => 11, 'code' => 120, 'name' => 'CABRERA'],
            ['departament_id' => 11, 'code' => 123, 'name' => 'CACHIPAY'],
            ['departament_id' => 11, 'code' => 126, 'name' => 'CAJICA'],
            ['departament_id' => 11, 'code' => 148, 'name' => 'CAPARRAPI'],
            ['departament_id' => 11, 'code' => 151, 'name' => 'CAQUEZA'],
            ['departament_id' => 11, 'code' => 154, 'name' => 'CARMEN DE CARUPA'],
            ['departament_id' => 11, 'code' => 168, 'name' => 'CHAGUANI'],
            ['departament_id' => 11, 'code' => 175, 'name' => 'CHIA'],
            ['departament_id' => 11, 'code' => 178, 'name' => 'CHIPAQUE'],
            ['departament_id' => 11, 'code' => 181, 'name' => 'CHOACHI'],
            ['departament_id' => 11, 'code' => 183, 'name' => 'CHOCONTA'],
            ['departament_id' => 11, 'code' => 200, 'name' => 'COGUA'],
            ['departament_id' => 11, 'code' => 214, 'name' => 'COTA'],
            ['departament_id' => 11, 'code' => 224, 'name' => 'CUCUNUBA'],
            ['departament_id' => 11, 'code' => 245, 'name' => 'EL COLEGIO'],
            ['departament_id' => 11, 'code' => 258, 'name' => 'EL PEÑON'],
            ['departament_id' => 11, 'code' => 260, 'name' => 'EL ROSAL'],
            ['departament_id' => 11, 'code' => 269, 'name' => 'FACATATIVA'],
            ['departament_id' => 11, 'code' => 279, 'name' => 'FOMEQUE'],
            ['departament_id' => 11, 'code' => 281, 'name' => 'FOSCA'],
            ['departament_id' => 11, 'code' => 286, 'name' => 'FUNZA'],
            ['departament_id' => 11, 'code' => 288, 'name' => 'FUQUENE'],
            ['departament_id' => 11, 'code' => 290, 'name' => 'FUSAGASUGA'],
            ['departament_id' => 11, 'code' => 293, 'name' => 'GACHALA'],
            ['departament_id' => 11, 'code' => 295, 'name' => 'GACHANCIPA'],
            ['departament_id' => 11, 'code' => 297, 'name' => 'GACHETA'],
            ['departament_id' => 11, 'code' => 299, 'name' => 'GAMA'],
            ['departament_id' => 11, 'code' => 307, 'name' => 'GIRARDOT'],
            ['departament_id' => 11, 'code' => 312, 'name' => 'GRANADA'],
            ['departament_id' => 11, 'code' => 317, 'name' => 'GUACHETA'],
            ['departament_id' => 11, 'code' => 320, 'name' => 'GUADUAS'],
            ['departament_id' => 11, 'code' => 322, 'name' => 'GUASCA'],
            ['departament_id' => 11, 'code' => 324, 'name' => 'GUATAQUI'],
            ['departament_id' => 11, 'code' => 326, 'name' => 'GUATAVITA'],
            ['departament_id' => 11, 'code' => 328, 'name' => 'GUAYABAL DE SIQUIMA'],
            ['departament_id' => 11, 'code' => 335, 'name' => 'GUAYABETAL'],
            ['departament_id' => 11, 'code' => 339, 'name' => 'GUTIERREZ'],
            ['departament_id' => 11, 'code' => 368, 'name' => 'JERUSALEN'],
            ['departament_id' => 11, 'code' => 372, 'name' => 'JUNIN'],
            ['departament_id' => 11, 'code' => 377, 'name' => 'LA CALERA'],
            ['departament_id' => 11, 'code' => 386, 'name' => 'LA MESA'],
            ['departament_id' => 11, 'code' => 394, 'name' => 'LA PALMA'],
            ['departament_id' => 11, 'code' => 398, 'name' => 'LA PEÑA'],
            ['departament_id' => 11, 'code' => 402, 'name' => 'LA VEGA'],
            ['departament_id' => 11, 'code' => 407, 'name' => 'LENGUAZAQUE'],
            ['departament_id' => 11, 'code' => 426, 'name' => 'MACHETA'],
            ['departament_id' => 11, 'code' => 430, 'name' => 'MADRID'],
            ['departament_id' => 11, 'code' => 436, 'name' => 'MANTA'],
            ['departament_id' => 11, 'code' => 438, 'name' => 'MEDINA'],
            ['departament_id' => 11, 'code' => 473, 'name' => 'MOSQUERA'],
            ['departament_id' => 11, 'code' => 483, 'name' => 'NARIÑO'],
            ['departament_id' => 11, 'code' => 486, 'name' => 'NEMOCON'],
            ['departament_id' => 11, 'code' => 488, 'name' => 'NILO'],
            ['departament_id' => 11, 'code' => 489, 'name' => 'NIMAIMA'],
            ['departament_id' => 11, 'code' => 491, 'name' => 'NOCAIMA'],
            ['departament_id' => 11, 'code' => 506, 'name' => 'VENECIA (OSPINA PEREZ)'],
            ['departament_id' => 11, 'code' => 513, 'name' => 'PACHO'],
            ['departament_id' => 11, 'code' => 518, 'name' => 'PAIME'],
            ['departament_id' => 11, 'code' => 524, 'name' => 'PANDI'],
            ['departament_id' => 11, 'code' => 530, 'name' => 'PARATEBUENO'],
            ['departament_id' => 11, 'code' => 535, 'name' => 'PASCA'],
            ['departament_id' => 11, 'code' => 572, 'name' => 'PUERTO SALGAR'],
            ['departament_id' => 11, 'code' => 580, 'name' => 'PULI'],
            ['departament_id' => 11, 'code' => 592, 'name' => 'QUEBRADANEGRA'],
            ['departament_id' => 11, 'code' => 594, 'name' => 'QUETAME'],
            ['departament_id' => 11, 'code' => 596, 'name' => 'QUIPILE'],
            ['departament_id' => 11, 'code' => 599, 'name' => 'APULO (RAFAEL REYES)'],
            ['departament_id' => 11, 'code' => 612, 'name' => 'RICAURTE'],
            ['departament_id' => 11, 'code' => 645, 'name' => 'SAN ANTONIO DEL TEQUENDAMA'],
            ['departament_id' => 11, 'code' => 649, 'name' => 'SAN BERNARDO'],
            ['departament_id' => 11, 'code' => 653, 'name' => 'SAN CAYETANO'],
            ['departament_id' => 11, 'code' => 658, 'name' => 'SAN FRANCISCO'],
            ['departament_id' => 11, 'code' => 662, 'name' => 'SAN JUAN DE RIOSECO'],
            ['departament_id' => 11, 'code' => 718, 'name' => 'SASAIMA'],
            ['departament_id' => 11, 'code' => 736, 'name' => 'SESQUILE'],
            ['departament_id' => 11, 'code' => 740, 'name' => 'SIBATE'],
            ['departament_id' => 11, 'code' => 743, 'name' => 'SILVANIA'],
            ['departament_id' => 11, 'code' => 745, 'name' => 'SIMIJACA'],
            ['departament_id' => 11, 'code' => 754, 'name' => 'SOACHA'],
            ['departament_id' => 11, 'code' => 758, 'name' => 'SOPO'],
            ['departament_id' => 11, 'code' => 769, 'name' => 'SUBACHOQUE'],
            ['departament_id' => 11, 'code' => 772, 'name' => 'SUESCA'],
            ['departament_id' => 11, 'code' => 777, 'name' => 'SUPATA'],
            ['departament_id' => 11, 'code' => 779, 'name' => 'SUSA'],
            ['departament_id' => 11, 'code' => 781, 'name' => 'SUTATAUSA'],
            ['departament_id' => 11, 'code' => 785, 'name' => 'TABIO'],
            ['departament_id' => 11, 'code' => 793, 'name' => 'TAUSA'],
            ['departament_id' => 11, 'code' => 797, 'name' => 'TENA'],
            ['departament_id' => 11, 'code' => 799, 'name' => 'TENJO'],
            ['departament_id' => 11, 'code' => 805, 'name' => 'TIBACUY'],
            ['departament_id' => 11, 'code' => 807, 'name' => 'TIBIRITA'],
            ['departament_id' => 11, 'code' => 815, 'name' => 'TOCAIMA'],
            ['departament_id' => 11, 'code' => 817, 'name' => 'TOCANCIPA'],
            ['departament_id' => 11, 'code' => 823, 'name' => 'TOPAIPI'],
            ['departament_id' => 11, 'code' => 839, 'name' => 'UBALA'],
            ['departament_id' => 11, 'code' => 841, 'name' => 'UBAQUE'],
            ['departament_id' => 11, 'code' => 843, 'name' => 'UBATE'],
            ['departament_id' => 11, 'code' => 845, 'name' => 'UNE'],
            ['departament_id' => 11, 'code' => 851, 'name' => 'UTICA'],
            ['departament_id' => 11, 'code' => 862, 'name' => 'VERGARA'],
            ['departament_id' => 11, 'code' => 867, 'name' => 'VIANI'],
            ['departament_id' => 11, 'code' => 871, 'name' => 'VILLAGOMEZ'],
            ['departament_id' => 11, 'code' => 873, 'name' => 'VILLAPINZON'],
            ['departament_id' => 11, 'code' => 875, 'name' => 'VILLETA'],
            ['departament_id' => 11, 'code' => 878, 'name' => 'VIOTA'],
            ['departament_id' => 11, 'code' => 885, 'name' => 'YACOPI'],
            ['departament_id' => 11, 'code' => 898, 'name' => 'ZIPACON'],
            ['departament_id' => 11, 'code' => 899, 'name' => 'ZIPAQUIRA'],
            ['departament_id' => 12, 'code' => 1, 'name' => 'QUIBDO (SAN FRANCISCO DE QUIBDO)'],
            ['departament_id' => 12, 'code' => 6, 'name' => 'ACANDI'],
            ['departament_id' => 12, 'code' => 25, 'name' => 'ALTO BAUDO (PIE DE PATO)'],
            ['departament_id' => 12, 'code' => 50, 'name' => 'ATRATO'],
            ['departament_id' => 12, 'code' => 73, 'name' => 'BAGADO'],
            ['departament_id' => 12, 'code' => 75, 'name' => 'BAHIA SOLANO (MUTIS)'],
            ['departament_id' => 12, 'code' => 77, 'name' => 'BAJO BAUDO (PIZARRO)'],
            ['departament_id' => 12, 'code' => 99, 'name' => 'BOJAYA (BELLAVISTA)'],
            ['departament_id' => 12, 'code' => 135, 'name' => 'CANTON DE SAN PABLO (MANAGRU)'],
            ['departament_id' => 12, 'code' => 205, 'name' => 'CONDOTO'],
            ['departament_id' => 12, 'code' => 245, 'name' => 'EL CARMEN DE ATRATO'],
            ['departament_id' => 12, 'code' => 250, 'name' => 'LITORAL DEL BAJO SAN JUAN (SANTA GENOVEVA DE DOCORDO)'],
            ['departament_id' => 12, 'code' => 361, 'name' => 'ISTMINA'],
            ['departament_id' => 12, 'code' => 372, 'name' => 'JURADO'],
            ['departament_id' => 12, 'code' => 413, 'name' => 'LLORO'],
            ['departament_id' => 12, 'code' => 425, 'name' => 'MEDIO ATRATO'],
            ['departament_id' => 12, 'code' => 430, 'name' => 'MEDIO BAUDO'],
            ['departament_id' => 12, 'code' => 491, 'name' => 'NOVITA'],
            ['departament_id' => 12, 'code' => 495, 'name' => 'NUQUI'],
            ['departament_id' => 12, 'code' => 600, 'name' => 'RIOQUITO'],
            ['departament_id' => 12, 'code' => 615, 'name' => 'RIOSUCIO'],
            ['departament_id' => 12, 'code' => 660, 'name' => 'SAN JOSE DEL PALMAR'],
            ['departament_id' => 12, 'code' => 745, 'name' => 'SIPI'],
            ['departament_id' => 12, 'code' => 787, 'name' => 'TADO'],
            ['departament_id' => 12, 'code' => 800, 'name' => 'UNGUIA'],
            ['departament_id' => 12, 'code' => 810, 'name' => 'UNION PANAMERICANA'],
            ['departament_id' => 13, 'code' => 1, 'name' => 'NEIVA'],
            ['departament_id' => 13, 'code' => 6, 'name' => 'ACEVEDO'],
            ['departament_id' => 13, 'code' => 13, 'name' => 'AGRADO'],
            ['departament_id' => 13, 'code' => 16, 'name' => 'AIPE'],
            ['departament_id' => 13, 'code' => 20, 'name' => 'ALGECIRAS'],
            ['departament_id' => 13, 'code' => 26, 'name' => 'ALTAMIRA'],
            ['departament_id' => 13, 'code' => 78, 'name' => 'BARAYA'],
            ['departament_id' => 13, 'code' => 132, 'name' => 'CAMPOALEGRE'],
            ['departament_id' => 13, 'code' => 206, 'name' => 'COLOMBIA'],
            ['departament_id' => 13, 'code' => 244, 'name' => 'ELIAS'],
            ['departament_id' => 13, 'code' => 298, 'name' => 'GARZON'],
            ['departament_id' => 13, 'code' => 306, 'name' => 'GIGANTE'],
            ['departament_id' => 13, 'code' => 319, 'name' => 'GUADALUPE'],
            ['departament_id' => 13, 'code' => 349, 'name' => 'HOBO'],
            ['departament_id' => 13, 'code' => 357, 'name' => 'IQUIRA'],
            ['departament_id' => 13, 'code' => 359, 'name' => 'ISNOS (SAN JOSE DE ISNOS)'],
            ['departament_id' => 13, 'code' => 378, 'name' => 'LA ARGENTINA'],
            ['departament_id' => 13, 'code' => 396, 'name' => 'LA PLATA'],
            ['departament_id' => 13, 'code' => 483, 'name' => 'NATAGA'],
            ['departament_id' => 13, 'code' => 503, 'name' => 'OPORAPA'],
            ['departament_id' => 13, 'code' => 518, 'name' => 'PAICOL'],
            ['departament_id' => 13, 'code' => 524, 'name' => 'PALERMO'],
            ['departament_id' => 13, 'code' => 530, 'name' => 'PALESTINA'],
            ['departament_id' => 13, 'code' => 548, 'name' => 'PITAL'],
            ['departament_id' => 13, 'code' => 551, 'name' => 'PITALITO'],
            ['departament_id' => 13, 'code' => 615, 'name' => 'RIVERA'],
            ['departament_id' => 13, 'code' => 660, 'name' => 'SALADOBLANCO'],
            ['departament_id' => 13, 'code' => 668, 'name' => 'SAN AGUSTIN'],
            ['departament_id' => 13, 'code' => 676, 'name' => 'SANTA MARIA'],
            ['departament_id' => 13, 'code' => 770, 'name' => 'SUAZA'],
            ['departament_id' => 13, 'code' => 791, 'name' => 'TARQUI'],
            ['departament_id' => 13, 'code' => 797, 'name' => 'TESALIA'],
            ['departament_id' => 13, 'code' => 799, 'name' => 'TELLO'],
            ['departament_id' => 13, 'code' => 801, 'name' => 'TERUEL'],
            ['departament_id' => 13, 'code' => 807, 'name' => 'TIMANA'],
            ['departament_id' => 13, 'code' => 872, 'name' => 'VILLAVIEJA'],
            ['departament_id' => 13, 'code' => 885, 'name' => 'YAGUARA'],
            ['departament_id' => 14, 'code' => 1, 'name' => 'RIOHACHA'],
            ['departament_id' => 14, 'code' => 78, 'name' => 'BARRANCAS'],
            ['departament_id' => 14, 'code' => 90, 'name' => 'DIBULLA'],
            ['departament_id' => 14, 'code' => 98, 'name' => 'DISTRACCION'],
            ['departament_id' => 14, 'code' => 110, 'name' => 'EL MOLINO'],
            ['departament_id' => 14, 'code' => 279, 'name' => 'FONSECA'],
            ['departament_id' => 14, 'code' => 378, 'name' => 'HATONUEVO'],
            ['departament_id' => 14, 'code' => 420, 'name' => 'LA JAGUA DEL PILAR'],
            ['departament_id' => 14, 'code' => 430, 'name' => 'MAICAO'],
            ['departament_id' => 14, 'code' => 560, 'name' => 'MANAURE'],
            ['departament_id' => 14, 'code' => 650, 'name' => 'SAN JUAN DEL CESAR'],
            ['departament_id' => 14, 'code' => 847, 'name' => 'URIBIA'],
            ['departament_id' => 14, 'code' => 855, 'name' => 'URUMITA'],
            ['departament_id' => 14, 'code' => 874, 'name' => 'VILLANUEVA'],
            ['departament_id' => 15, 'code' => 1, 'name' => 'SANTA MARTA (DISTRITO TURISTICO CULTURAL E HISTORICO DE SANTA MARTA)'],
            ['departament_id' => 15, 'code' => 30, 'name' => 'ALGARROBO'],
            ['departament_id' => 15, 'code' => 53, 'name' => 'ARACATACA'],
            ['departament_id' => 15, 'code' => 58, 'name' => 'ARIGUANI (EL DIFICIL)'],
            ['departament_id' => 15, 'code' => 161, 'name' => 'CERRO SAN ANTONIO'],
            ['departament_id' => 15, 'code' => 170, 'name' => 'CHIVOLO'],
            ['departament_id' => 15, 'code' => 189, 'name' => 'CIENAGA'],
            ['departament_id' => 15, 'code' => 205, 'name' => 'CONCORDIA'],
            ['departament_id' => 15, 'code' => 245, 'name' => 'EL BANCO'],
            ['departament_id' => 15, 'code' => 258, 'name' => 'EL PIÑON'],
            ['departament_id' => 15, 'code' => 268, 'name' => 'EL RETEN'],
            ['departament_id' => 15, 'code' => 288, 'name' => 'FUNDACION'],
            ['departament_id' => 15, 'code' => 318, 'name' => 'GUAMAL'],
            ['departament_id' => 15, 'code' => 541, 'name' => 'PEDRAZA'],
            ['departament_id' => 15, 'code' => 545, 'name' => 'PIJIÑO DEL CARMEN (PIJIÑO)'],
            ['departament_id' => 15, 'code' => 551, 'name' => 'PIVIJAY'],
            ['departament_id' => 15, 'code' => 555, 'name' => 'PLATO'],
            ['departament_id' => 15, 'code' => 570, 'name' => 'PUEBLOVIEJO'],
            ['departament_id' => 15, 'code' => 605, 'name' => 'REMOLINO'],
            ['departament_id' => 15, 'code' => 660, 'name' => 'SABANAS DE SAN ANGEL'],
            ['departament_id' => 15, 'code' => 675, 'name' => 'SALAMINA'],
            ['departament_id' => 15, 'code' => 692, 'name' => 'SAN SEBASTIAN DE BUENAVISTA'],
            ['departament_id' => 15, 'code' => 703, 'name' => 'SAN ZENON'],
            ['departament_id' => 15, 'code' => 707, 'name' => 'SANTA ANA'],
            ['departament_id' => 15, 'code' => 745, 'name' => 'SITIONUEVO'],
            ['departament_id' => 15, 'code' => 798, 'name' => 'TENERIFE'],
            ['departament_id' => 16, 'code' => 1, 'name' => 'VILLAVICENCIO'],
            ['departament_id' => 16, 'code' => 6, 'name' => 'ACACIAS'],
            ['departament_id' => 16, 'code' => 110, 'name' => 'BARRANCA DE UPIA'],
            ['departament_id' => 16, 'code' => 124, 'name' => 'CABUYARO'],
            ['departament_id' => 16, 'code' => 150, 'name' => 'CASTILLA LA NUEVA'],
            ['departament_id' => 16, 'code' => 223, 'name' => 'SAN LUIS DE CUBARRAL'],
            ['departament_id' => 16, 'code' => 226, 'name' => 'CUMARAL'],
            ['departament_id' => 16, 'code' => 245, 'name' => 'EL CALVARIO'],
            ['departament_id' => 16, 'code' => 251, 'name' => 'EL CASTILLO'],
            ['departament_id' => 16, 'code' => 270, 'name' => 'EL DORADO'],
            ['departament_id' => 16, 'code' => 287, 'name' => 'FUENTE DE ORO'],
            ['departament_id' => 16, 'code' => 313, 'name' => 'GRANADA'],
            ['departament_id' => 16, 'code' => 318, 'name' => 'GUAMAL'],
            ['departament_id' => 16, 'code' => 325, 'name' => 'MAPIRIPAN'],
            ['departament_id' => 16, 'code' => 330, 'name' => 'MESETAS'],
            ['departament_id' => 16, 'code' => 350, 'name' => 'LA MACARENA'],
            ['departament_id' => 16, 'code' => 370, 'name' => 'LA URIBE'],
            ['departament_id' => 16, 'code' => 400, 'name' => 'LEJANIAS'],
            ['departament_id' => 16, 'code' => 450, 'name' => 'PUERTO CONCORDIA'],
            ['departament_id' => 16, 'code' => 568, 'name' => 'PUERTO GAITAN'],
            ['departament_id' => 16, 'code' => 573, 'name' => 'PUERTO LOPEZ'],
            ['departament_id' => 16, 'code' => 577, 'name' => 'PUERTO LLERAS'],
            ['departament_id' => 16, 'code' => 590, 'name' => 'PUERTO RICO'],
            ['departament_id' => 16, 'code' => 606, 'name' => 'RESTREPO'],
            ['departament_id' => 16, 'code' => 680, 'name' => 'SAN CARLOS DE GUAROA'],
            ['departament_id' => 16, 'code' => 683, 'name' => 'SAN JUAN DE ARAMA'],
            ['departament_id' => 16, 'code' => 686, 'name' => 'SAN JUANITO'],
            ['departament_id' => 16, 'code' => 689, 'name' => 'SAN MARTIN'],
            ['departament_id' => 16, 'code' => 711, 'name' => 'VISTAHERMOSA'],
            ['departament_id' => 17, 'code' => 1, 'name' => 'PASTO (SAN JUAN DE PASTO)'],
            ['departament_id' => 17, 'code' => 19, 'name' => 'ALBAN (SAN JOSE)'],
            ['departament_id' => 17, 'code' => 22, 'name' => 'ALDANA'],
            ['departament_id' => 17, 'code' => 36, 'name' => 'ANCUYA'],
            ['departament_id' => 17, 'code' => 51, 'name' => 'ARBOLEDA (BERRUECOS)'],
            ['departament_id' => 17, 'code' => 79, 'name' => 'BARBACOAS'],
            ['departament_id' => 17, 'code' => 83, 'name' => 'BELEN'],
            ['departament_id' => 17, 'code' => 110, 'name' => 'BUESACO'],
            ['departament_id' => 17, 'code' => 203, 'name' => 'COLON (GENOVA)'],
            ['departament_id' => 17, 'code' => 207, 'name' => 'CONSACA'],
            ['departament_id' => 17, 'code' => 210, 'name' => 'CONTADERO'],
            ['departament_id' => 17, 'code' => 215, 'name' => 'CORDOBA'],
            ['departament_id' => 17, 'code' => 224, 'name' => 'CUASPUD (CARLOSAMA)'],
            ['departament_id' => 17, 'code' => 227, 'name' => 'CUMBAL'],
            ['departament_id' => 17, 'code' => 233, 'name' => 'CUMBITARA'],
            ['departament_id' => 17, 'code' => 240, 'name' => 'CHACHAGUI'],
            ['departament_id' => 17, 'code' => 250, 'name' => 'EL CHARCO'],
            ['departament_id' => 17, 'code' => 254, 'name' => 'EL PEÑOL'],
            ['departament_id' => 17, 'code' => 256, 'name' => 'EL ROSARIO'],
            ['departament_id' => 17, 'code' => 258, 'name' => 'EL TABLON'],
            ['departament_id' => 17, 'code' => 260, 'name' => 'EL TAMBO'],
            ['departament_id' => 17, 'code' => 287, 'name' => 'FUNES'],
            ['departament_id' => 17, 'code' => 317, 'name' => 'GUACHUCAL'],
            ['departament_id' => 17, 'code' => 320, 'name' => 'GUAITARILLA'],
            ['departament_id' => 17, 'code' => 323, 'name' => 'GUALMATAN'],
            ['departament_id' => 17, 'code' => 352, 'name' => 'ILES'],
            ['departament_id' => 17, 'code' => 354, 'name' => 'IMUES'],
            ['departament_id' => 17, 'code' => 356, 'name' => 'IPIALES'],
            ['departament_id' => 17, 'code' => 378, 'name' => 'LA CRUZ'],
            ['departament_id' => 17, 'code' => 381, 'name' => 'LA FLORIDA'],
            ['departament_id' => 17, 'code' => 385, 'name' => 'LA LLANADA'],
            ['departament_id' => 17, 'code' => 390, 'name' => 'LA TOLA'],
            ['departament_id' => 17, 'code' => 399, 'name' => 'LA UNION'],
            ['departament_id' => 17, 'code' => 405, 'name' => 'LEIVA'],
            ['departament_id' => 17, 'code' => 411, 'name' => 'LINARES'],
            ['departament_id' => 17, 'code' => 418, 'name' => 'LOS ANDES (SOTOMAYOR)'],
            ['departament_id' => 17, 'code' => 427, 'name' => 'MAGUI (PAYAN)'],
            ['departament_id' => 17, 'code' => 435, 'name' => 'MALLAMA (PIEDRANCHA)'],
            ['departament_id' => 17, 'code' => 473, 'name' => 'MOSQUERA'],
            ['departament_id' => 17, 'code' => 490, 'name' => 'OLAYA HERRERA (BOCAS DE SATINGA)'],
            ['departament_id' => 17, 'code' => 506, 'name' => 'OSPINA'],
            ['departament_id' => 17, 'code' => 520, 'name' => 'FRANCISCO PIZARRO (SALAHONDA)'],
            ['departament_id' => 17, 'code' => 540, 'name' => 'POLICARPA'],
            ['departament_id' => 17, 'code' => 560, 'name' => 'POTOSI'],
            ['departament_id' => 17, 'code' => 565, 'name' => 'PROVIDENCIA'],
            ['departament_id' => 17, 'code' => 573, 'name' => 'PUERRES'],
            ['departament_id' => 17, 'code' => 585, 'name' => 'PUPIALES'],
            ['departament_id' => 17, 'code' => 612, 'name' => 'RICAURTE'],
            ['departament_id' => 17, 'code' => 621, 'name' => 'ROBERTO PAYAN (SAN JOSE)'],
            ['departament_id' => 17, 'code' => 678, 'name' => 'SAMANIEGO'],
            ['departament_id' => 17, 'code' => 683, 'name' => 'SANDONA'],
            ['departament_id' => 17, 'code' => 685, 'name' => 'SAN BERNARDO'],
            ['departament_id' => 17, 'code' => 687, 'name' => 'SAN LORENZO'],
            ['departament_id' => 17, 'code' => 693, 'name' => 'SAN PABLO'],
            ['departament_id' => 17, 'code' => 694, 'name' => 'SAN PEDRO DE CARTAGO'],
            ['departament_id' => 17, 'code' => 696, 'name' => 'SANTA BARBARA (ISCUANDE)'],
            ['departament_id' => 17, 'code' => 699, 'name' => 'SANTA CRUZ (GUACHAVES)'],
            ['departament_id' => 17, 'code' => 720, 'name' => 'SAPUYES'],
            ['departament_id' => 17, 'code' => 786, 'name' => 'TAMINANGO'],
            ['departament_id' => 17, 'code' => 788, 'name' => 'TANGUA'],
            ['departament_id' => 17, 'code' => 835, 'name' => 'TUMACO'],
            ['departament_id' => 17, 'code' => 838, 'name' => 'TUQUERRES'],
            ['departament_id' => 17, 'code' => 885, 'name' => 'YACUANQUER'],
            ['departament_id' => 18, 'code' => 1, 'name' => 'CUCUTA'],
            ['departament_id' => 18, 'code' => 3, 'name' => 'ABREGO'],
            ['departament_id' => 18, 'code' => 51, 'name' => 'ARBOLEDAS'],
            ['departament_id' => 18, 'code' => 99, 'name' => 'BOCHALEMA'],
            ['departament_id' => 18, 'code' => 109, 'name' => 'BUCARASICA'],
            ['departament_id' => 18, 'code' => 125, 'name' => 'CACOTA'],
            ['departament_id' => 18, 'code' => 128, 'name' => 'CACHIRA'],
            ['departament_id' => 18, 'code' => 172, 'name' => 'CHINACOTA'],
            ['departament_id' => 18, 'code' => 174, 'name' => 'CHITAGA'],
            ['departament_id' => 18, 'code' => 206, 'name' => 'CONVENCION'],
            ['departament_id' => 18, 'code' => 223, 'name' => 'CUCUTILLA'],
            ['departament_id' => 18, 'code' => 239, 'name' => 'DURANIA'],
            ['departament_id' => 18, 'code' => 245, 'name' => 'EL CARMEN'],
            ['departament_id' => 18, 'code' => 250, 'name' => 'EL TARRA'],
            ['departament_id' => 18, 'code' => 261, 'name' => 'EL ZULIA'],
            ['departament_id' => 18, 'code' => 313, 'name' => 'GRAMALOTE'],
            ['departament_id' => 18, 'code' => 344, 'name' => 'HACARI'],
            ['departament_id' => 18, 'code' => 347, 'name' => 'HERRAN'],
            ['departament_id' => 18, 'code' => 377, 'name' => 'LABATECA'],
            ['departament_id' => 18, 'code' => 385, 'name' => 'LA ESPERANZA'],
            ['departament_id' => 18, 'code' => 398, 'name' => 'LA PLAYA'],
            ['departament_id' => 18, 'code' => 405, 'name' => 'LOS PATIOS'],
            ['departament_id' => 18, 'code' => 418, 'name' => 'LOURDES'],
            ['departament_id' => 18, 'code' => 480, 'name' => 'MUTISCUA'],
            ['departament_id' => 18, 'code' => 498, 'name' => 'OCAÑA'],
            ['departament_id' => 18, 'code' => 518, 'name' => 'PAMPLONA'],
            ['departament_id' => 18, 'code' => 520, 'name' => 'PAMPLONITA'],
            ['departament_id' => 18, 'code' => 553, 'name' => 'PUERTO SANTANDER'],
            ['departament_id' => 18, 'code' => 599, 'name' => 'RAGONVALIA'],
            ['departament_id' => 18, 'code' => 660, 'name' => 'SALAZAR'],
            ['departament_id' => 18, 'code' => 670, 'name' => 'SAN CALIXTO'],
            ['departament_id' => 18, 'code' => 673, 'name' => 'SAN CAYETANO'],
            ['departament_id' => 18, 'code' => 680, 'name' => 'SANTIAGO'],
            ['departament_id' => 18, 'code' => 720, 'name' => 'SARDINATA'],
            ['departament_id' => 18, 'code' => 743, 'name' => 'SILOS'],
            ['departament_id' => 18, 'code' => 800, 'name' => 'TEORAMA'],
            ['departament_id' => 18, 'code' => 810, 'name' => 'TIBU'],
            ['departament_id' => 18, 'code' => 820, 'name' => 'TOLEDO'],
            ['departament_id' => 18, 'code' => 871, 'name' => 'VILLACARO'],
            ['departament_id' => 18, 'code' => 874, 'name' => 'VILLA DEL ROSARIO'],
            ['departament_id' => 19, 'code' => 1, 'name' => 'ARMENIA'],
            ['departament_id' => 19, 'code' => 111, 'name' => 'BUENAVISTA'],
            ['departament_id' => 19, 'code' => 130, 'name' => 'CALARCA'],
            ['departament_id' => 19, 'code' => 190, 'name' => 'CIRCASIA'],
            ['departament_id' => 19, 'code' => 212, 'name' => 'CORDOBA'],
            ['departament_id' => 19, 'code' => 272, 'name' => 'FILANDIA'],
            ['departament_id' => 19, 'code' => 302, 'name' => 'GENOVA'],
            ['departament_id' => 19, 'code' => 401, 'name' => 'LA TEBAIDA'],
            ['departament_id' => 19, 'code' => 470, 'name' => 'MONTENEGRO'],
            ['departament_id' => 19, 'code' => 548, 'name' => 'PIJAO'],
            ['departament_id' => 19, 'code' => 594, 'name' => 'QUIMBAYA'],
            ['departament_id' => 19, 'code' => 690, 'name' => 'SALENTO'],
            ['departament_id' => 20, 'code' => 1, 'name' => 'PEREIRA'],
            ['departament_id' => 20, 'code' => 45, 'name' => 'APIA'],
            ['departament_id' => 20, 'code' => 75, 'name' => 'BALBOA'],
            ['departament_id' => 20, 'code' => 88, 'name' => 'BELEN DE UMBRIA'],
            ['departament_id' => 20, 'code' => 170, 'name' => 'DOS QUEBRADAS'],
            ['departament_id' => 20, 'code' => 318, 'name' => 'GUATICA'],
            ['departament_id' => 20, 'code' => 383, 'name' => 'LA CELIA'],
            ['departament_id' => 20, 'code' => 400, 'name' => 'LA VIRGINIA'],
            ['departament_id' => 20, 'code' => 440, 'name' => 'MARSELLA'],
            ['departament_id' => 20, 'code' => 456, 'name' => 'MISTRATO'],
            ['departament_id' => 20, 'code' => 572, 'name' => 'PUEBLO RICO'],
            ['departament_id' => 20, 'code' => 594, 'name' => 'QUINCHIA'],
            ['departament_id' => 20, 'code' => 682, 'name' => 'SANTA ROSA DE CABAL'],
            ['departament_id' => 20, 'code' => 687, 'name' => 'SANTUARIO'],
            ['departament_id' => 21, 'code' => 1, 'name' => 'BUCARAMANGA'],
            ['departament_id' => 21, 'code' => 13, 'name' => 'AGUADA'],
            ['departament_id' => 21, 'code' => 20, 'name' => 'ALBANIA'],
            ['departament_id' => 21, 'code' => 51, 'name' => 'ARATOCA'],
            ['departament_id' => 21, 'code' => 77, 'name' => 'BARBOSA'],
            ['departament_id' => 21, 'code' => 79, 'name' => 'BARICHARA'],
            ['departament_id' => 21, 'code' => 81, 'name' => 'BARRANCABERMEJA'],
            ['departament_id' => 21, 'code' => 92, 'name' => 'BETULIA'],
            ['departament_id' => 21, 'code' => 101, 'name' => 'BOLIVAR'],
            ['departament_id' => 21, 'code' => 121, 'name' => 'CABRERA'],
            ['departament_id' => 21, 'code' => 132, 'name' => 'CALIFORNIA'],
            ['departament_id' => 21, 'code' => 147, 'name' => 'CAPITANEJO'],
            ['departament_id' => 21, 'code' => 152, 'name' => 'CARCASI'],
            ['departament_id' => 21, 'code' => 160, 'name' => 'CEPITA'],
            ['departament_id' => 21, 'code' => 162, 'name' => 'CERRITO'],
            ['departament_id' => 21, 'code' => 167, 'name' => 'CHARALA'],
            ['departament_id' => 21, 'code' => 169, 'name' => 'CHARTA'],
            ['departament_id' => 21, 'code' => 176, 'name' => 'CHIMA'],
            ['departament_id' => 21, 'code' => 179, 'name' => 'CHIPATA'],
            ['departament_id' => 21, 'code' => 190, 'name' => 'CIMITARRA'],
            ['departament_id' => 21, 'code' => 207, 'name' => 'CONCEPCION'],
            ['departament_id' => 21, 'code' => 209, 'name' => 'CONFINES'],
            ['departament_id' => 21, 'code' => 211, 'name' => 'CONTRATACION'],
            ['departament_id' => 21, 'code' => 217, 'name' => 'COROMORO'],
            ['departament_id' => 21, 'code' => 229, 'name' => 'CURITI'],
            ['departament_id' => 21, 'code' => 235, 'name' => 'EL CARMEN DE CHUCURY'],
            ['departament_id' => 21, 'code' => 245, 'name' => 'EL GUACAMAYO'],
            ['departament_id' => 21, 'code' => 250, 'name' => 'EL PEÑON'],
            ['departament_id' => 21, 'code' => 255, 'name' => 'EL PLAYON'],
            ['departament_id' => 21, 'code' => 264, 'name' => 'ENCINO'],
            ['departament_id' => 21, 'code' => 266, 'name' => 'ENCISO'],
            ['departament_id' => 21, 'code' => 271, 'name' => 'FLORIAN'],
            ['departament_id' => 21, 'code' => 276, 'name' => 'FLORIDABLANCA'],
            ['departament_id' => 21, 'code' => 296, 'name' => 'GALAN'],
            ['departament_id' => 21, 'code' => 298, 'name' => 'GAMBITA'],
            ['departament_id' => 21, 'code' => 307, 'name' => 'GIRON'],
            ['departament_id' => 21, 'code' => 318, 'name' => 'GUACA'],
            ['departament_id' => 21, 'code' => 320, 'name' => 'GUADALUPE'],
            ['departament_id' => 21, 'code' => 322, 'name' => 'GUAPOTA'],
            ['departament_id' => 21, 'code' => 324, 'name' => 'GUAVATA'],
            ['departament_id' => 21, 'code' => 327, 'name' => 'GUEPSA'],
            ['departament_id' => 21, 'code' => 344, 'name' => 'HATO'],
            ['departament_id' => 21, 'code' => 368, 'name' => 'JESUS MARIA'],
            ['departament_id' => 21, 'code' => 370, 'name' => 'JORDAN'],
            ['departament_id' => 21, 'code' => 377, 'name' => 'LA BELLEZA'],
            ['departament_id' => 21, 'code' => 385, 'name' => 'LANDAZURI'],
            ['departament_id' => 21, 'code' => 397, 'name' => 'LA PAZ'],
            ['departament_id' => 21, 'code' => 406, 'name' => 'LEBRIJA'],
            ['departament_id' => 21, 'code' => 418, 'name' => 'LOS SANTOS'],
            ['departament_id' => 21, 'code' => 425, 'name' => 'MACARAVITA'],
            ['departament_id' => 21, 'code' => 432, 'name' => 'MALAGA'],
            ['departament_id' => 21, 'code' => 444, 'name' => 'MATANZA'],
            ['departament_id' => 21, 'code' => 464, 'name' => 'MOGOTES'],
            ['departament_id' => 21, 'code' => 468, 'name' => 'MOLAGAVITA'],
            ['departament_id' => 21, 'code' => 498, 'name' => 'OCAMONTE'],
            ['departament_id' => 21, 'code' => 500, 'name' => 'OIBA'],
            ['departament_id' => 21, 'code' => 502, 'name' => 'ONZAGA'],
            ['departament_id' => 21, 'code' => 522, 'name' => 'PALMAR'],
            ['departament_id' => 21, 'code' => 524, 'name' => 'PALMAS DEL SOCORRO'],
            ['departament_id' => 21, 'code' => 533, 'name' => 'PARAMO'],
            ['departament_id' => 21, 'code' => 547, 'name' => 'PIEDECUESTA'],
            ['departament_id' => 21, 'code' => 549, 'name' => 'PINCHOTE'],
            ['departament_id' => 21, 'code' => 572, 'name' => 'PUENTE NACIONAL'],
            ['departament_id' => 21, 'code' => 573, 'name' => 'PUERTO PARRA'],
            ['departament_id' => 21, 'code' => 575, 'name' => 'PUERTO WILCHES'],
            ['departament_id' => 21, 'code' => 615, 'name' => 'RIONEGRO'],
            ['departament_id' => 21, 'code' => 655, 'name' => 'SABANA DE TORRES'],
            ['departament_id' => 21, 'code' => 669, 'name' => 'SAN ANDRES'],
            ['departament_id' => 21, 'code' => 673, 'name' => 'SAN BENITO'],
            ['departament_id' => 21, 'code' => 679, 'name' => 'SAN GIL'],
            ['departament_id' => 21, 'code' => 682, 'name' => 'SAN JOAQUIN'],
            ['departament_id' => 21, 'code' => 684, 'name' => 'SAN JOSE DE MIRANDA'],
            ['departament_id' => 21, 'code' => 686, 'name' => 'SAN MIGUEL'],
            ['departament_id' => 21, 'code' => 689, 'name' => 'SAN VICENTE DE CHUCURI'],
            ['departament_id' => 21, 'code' => 705, 'name' => 'SANTA BARBARA'],
            ['departament_id' => 21, 'code' => 720, 'name' => 'SANTA HELENA DEL OPON'],
            ['departament_id' => 21, 'code' => 745, 'name' => 'SIMACOTA'],
            ['departament_id' => 21, 'code' => 755, 'name' => 'SOCORRO'],
            ['departament_id' => 21, 'code' => 770, 'name' => 'SUAITA'],
            ['departament_id' => 21, 'code' => 773, 'name' => 'SUCRE'],
            ['departament_id' => 21, 'code' => 780, 'name' => 'SURATA'],
            ['departament_id' => 21, 'code' => 820, 'name' => 'TONA'],
            ['departament_id' => 21, 'code' => 855, 'name' => 'VALLE SAN JOSE'],
            ['departament_id' => 21, 'code' => 861, 'name' => 'VELEZ'],
            ['departament_id' => 21, 'code' => 867, 'name' => 'VETAS'],
            ['departament_id' => 21, 'code' => 872, 'name' => 'VILLANUEVA'],
            ['departament_id' => 21, 'code' => 895, 'name' => 'ZAPATOCA'],
            ['departament_id' => 22, 'code' => 1, 'name' => 'SINCELEJO'],
            ['departament_id' => 22, 'code' => 110, 'name' => 'BUENAVISTA'],
            ['departament_id' => 22, 'code' => 124, 'name' => 'CAIMITO'],
            ['departament_id' => 22, 'code' => 204, 'name' => 'COLOSO (RICAURTE)'],
            ['departament_id' => 22, 'code' => 215, 'name' => 'COROZAL'],
            ['departament_id' => 22, 'code' => 230, 'name' => 'CHALAN'],
            ['departament_id' => 22, 'code' => 235, 'name' => 'GALERAS (NUEVA GRANADA)'],
            ['departament_id' => 22, 'code' => 265, 'name' => 'GUARANDA'],
            ['departament_id' => 22, 'code' => 400, 'name' => 'LA UNION'],
            ['departament_id' => 22, 'code' => 418, 'name' => 'LOS PALMITOS'],
            ['departament_id' => 22, 'code' => 429, 'name' => 'MAJAGUAL'],
            ['departament_id' => 22, 'code' => 473, 'name' => 'MORROA'],
            ['departament_id' => 22, 'code' => 508, 'name' => 'OVEJAS'],
            ['departament_id' => 22, 'code' => 523, 'name' => 'PALMITO'],
            ['departament_id' => 22, 'code' => 670, 'name' => 'SAMPUES'],
            ['departament_id' => 22, 'code' => 678, 'name' => 'SAN BENITO ABAD'],
            ['departament_id' => 22, 'code' => 702, 'name' => 'SAN JUAN DE BETULIA'],
            ['departament_id' => 22, 'code' => 708, 'name' => 'SAN MARCOS'],
            ['departament_id' => 22, 'code' => 713, 'name' => 'SAN ONOFRE'],
            ['departament_id' => 22, 'code' => 717, 'name' => 'SAN PEDRO'],
            ['departament_id' => 22, 'code' => 742, 'name' => 'SINCE'],
            ['departament_id' => 22, 'code' => 771, 'name' => 'SUCRE'],
            ['departament_id' => 22, 'code' => 820, 'name' => 'TOLU'],
            ['departament_id' => 22, 'code' => 823, 'name' => 'TOLUVIEJO'],
            ['departament_id' => 23, 'code' => 1, 'name' => 'IBAGUE'],
            ['departament_id' => 23, 'code' => 24, 'name' => 'ALPUJARRA'],
            ['departament_id' => 23, 'code' => 26, 'name' => 'ALVARADO'],
            ['departament_id' => 23, 'code' => 30, 'name' => 'AMBALEMA'],
            ['departament_id' => 23, 'code' => 43, 'name' => 'ANZOATEGUI'],
            ['departament_id' => 23, 'code' => 55, 'name' => 'ARMERO (GUAYABAL)'],
            ['departament_id' => 23, 'code' => 67, 'name' => 'ATACO'],
            ['departament_id' => 23, 'code' => 124, 'name' => 'CAJAMARCA'],
            ['departament_id' => 23, 'code' => 148, 'name' => 'CARMEN APICALA'],
            ['departament_id' => 23, 'code' => 152, 'name' => 'CASABIANCA'],
            ['departament_id' => 23, 'code' => 168, 'name' => 'CHAPARRAL'],
            ['departament_id' => 23, 'code' => 200, 'name' => 'COELLO'],
            ['departament_id' => 23, 'code' => 217, 'name' => 'COYAIMA'],
            ['departament_id' => 23, 'code' => 226, 'name' => 'CUNDAY'],
            ['departament_id' => 23, 'code' => 236, 'name' => 'DOLORES'],
            ['departament_id' => 23, 'code' => 268, 'name' => 'ESPINAL'],
            ['departament_id' => 23, 'code' => 270, 'name' => 'FALAN'],
            ['departament_id' => 23, 'code' => 275, 'name' => 'FLANDES'],
            ['departament_id' => 23, 'code' => 283, 'name' => 'FRESNO'],
            ['departament_id' => 23, 'code' => 319, 'name' => 'GUAMO'],
            ['departament_id' => 23, 'code' => 347, 'name' => 'HERVEO'],
            ['departament_id' => 23, 'code' => 349, 'name' => 'HONDA'],
            ['departament_id' => 23, 'code' => 352, 'name' => 'ICONONZO'],
            ['departament_id' => 23, 'code' => 408, 'name' => 'LERIDA'],
            ['departament_id' => 23, 'code' => 411, 'name' => 'LIBANO'],
            ['departament_id' => 23, 'code' => 443, 'name' => 'MARIQUITA'],
            ['departament_id' => 23, 'code' => 449, 'name' => 'MELGAR'],
            ['departament_id' => 23, 'code' => 461, 'name' => 'MURILLO'],
            ['departament_id' => 23, 'code' => 483, 'name' => 'NATAGAIMA'],
            ['departament_id' => 23, 'code' => 504, 'name' => 'ORTEGA'],
            ['departament_id' => 23, 'code' => 520, 'name' => 'PALOCABILDO'],
            ['departament_id' => 23, 'code' => 547, 'name' => 'PIEDRAS'],
            ['departament_id' => 23, 'code' => 555, 'name' => 'PLANADAS'],
            ['departament_id' => 23, 'code' => 563, 'name' => 'PRADO'],
            ['departament_id' => 23, 'code' => 585, 'name' => 'PURIFICACION'],
            ['departament_id' => 23, 'code' => 616, 'name' => 'RIOBLANCO'],
            ['departament_id' => 23, 'code' => 622, 'name' => 'RONCESVALLES'],
            ['departament_id' => 23, 'code' => 624, 'name' => 'ROVIRA'],
            ['departament_id' => 23, 'code' => 671, 'name' => 'SALDAÑA'],
            ['departament_id' => 23, 'code' => 675, 'name' => 'SAN ANTONIO'],
            ['departament_id' => 23, 'code' => 678, 'name' => 'SAN LUIS'],
            ['departament_id' => 23, 'code' => 686, 'name' => 'SANTA ISABEL'],
            ['departament_id' => 23, 'code' => 770, 'name' => 'SUAREZ'],
            ['departament_id' => 23, 'code' => 854, 'name' => 'VALLE DE SAN JUAN'],
            ['departament_id' => 23, 'code' => 861, 'name' => 'VENADILLO'],
            ['departament_id' => 23, 'code' => 870, 'name' => 'VILLAHERMOSA'],
            ['departament_id' => 23, 'code' => 873, 'name' => 'VILLARRICA'],
            ['departament_id' => 24, 'code' => 1, 'name' => 'CALI (SANTIAGO DE CALI)'],
            ['departament_id' => 24, 'code' => 20, 'name' => 'ALCALA'],
            ['departament_id' => 24, 'code' => 36, 'name' => 'ANDALUCIA'],
            ['departament_id' => 24, 'code' => 41, 'name' => 'ANSERMANUEVO'],
            ['departament_id' => 24, 'code' => 54, 'name' => 'ARGELIA'],
            ['departament_id' => 24, 'code' => 100, 'name' => 'BOLIVAR'],
            ['departament_id' => 24, 'code' => 109, 'name' => 'BUENAVENTURA'],
            ['departament_id' => 24, 'code' => 111, 'name' => 'BUGA'],
            ['departament_id' => 24, 'code' => 113, 'name' => 'BUGALAGRANDE'],
            ['departament_id' => 24, 'code' => 122, 'name' => 'CAICEDONIA'],
            ['departament_id' => 24, 'code' => 126, 'name' => 'CALIMA (DARIEN)'],
            ['departament_id' => 24, 'code' => 130, 'name' => 'CANDELARIA'],
            ['departament_id' => 24, 'code' => 147, 'name' => 'CARTAGO'],
            ['departament_id' => 24, 'code' => 233, 'name' => 'DAGUA'],
            ['departament_id' => 24, 'code' => 243, 'name' => 'EL AGUILA'],
            ['departament_id' => 24, 'code' => 246, 'name' => 'EL CAIRO'],
            ['departament_id' => 24, 'code' => 248, 'name' => 'EL CERRITO'],
            ['departament_id' => 24, 'code' => 250, 'name' => 'EL DOVIO'],
            ['departament_id' => 24, 'code' => 275, 'name' => 'FLORIDA'],
            ['departament_id' => 24, 'code' => 306, 'name' => 'GINEBRA'],
            ['departament_id' => 24, 'code' => 318, 'name' => 'GUACARI'],
            ['departament_id' => 24, 'code' => 364, 'name' => 'JAMUNDI'],
            ['departament_id' => 24, 'code' => 377, 'name' => 'LA CUMBRE'],
            ['departament_id' => 24, 'code' => 400, 'name' => 'LA UNION'],
            ['departament_id' => 24, 'code' => 403, 'name' => 'LA VICTORIA'],
            ['departament_id' => 24, 'code' => 497, 'name' => 'OBANDO'],
            ['departament_id' => 24, 'code' => 520, 'name' => 'PALMIRA'],
            ['departament_id' => 24, 'code' => 563, 'name' => 'PRADERA'],
            ['departament_id' => 24, 'code' => 606, 'name' => 'RESTREPO'],
            ['departament_id' => 24, 'code' => 616, 'name' => 'RIOFRIO'],
            ['departament_id' => 24, 'code' => 622, 'name' => 'ROLDANILLO'],
            ['departament_id' => 24, 'code' => 670, 'name' => 'SAN PEDRO'],
            ['departament_id' => 24, 'code' => 736, 'name' => 'SEVILLA'],
            ['departament_id' => 24, 'code' => 823, 'name' => 'TORO'],
            ['departament_id' => 24, 'code' => 828, 'name' => 'TRUJILLO'],
            ['departament_id' => 24, 'code' => 834, 'name' => 'TULUA'],
            ['departament_id' => 24, 'code' => 845, 'name' => 'ULLOA'],
            ['departament_id' => 24, 'code' => 863, 'name' => 'VERSALLES'],
            ['departament_id' => 24, 'code' => 869, 'name' => 'VIJES'],
            ['departament_id' => 24, 'code' => 890, 'name' => 'YOTOCO'],
            ['departament_id' => 24, 'code' => 892, 'name' => 'YUMBO'],
            ['departament_id' => 24, 'code' => 895, 'name' => 'ZARZAL'],
            ['departament_id' => 25, 'code' => 1, 'name' => 'ARAUCA'],
            ['departament_id' => 25, 'code' => 65, 'name' => 'ARAUQUITA'],
            ['departament_id' => 25, 'code' => 220, 'name' => 'CRAVO NORTE'],
            ['departament_id' => 25, 'code' => 300, 'name' => 'FORTUL'],
            ['departament_id' => 25, 'code' => 591, 'name' => 'PUERTO RONDON'],
            ['departament_id' => 25, 'code' => 736, 'name' => 'SARAVENA'],
            ['departament_id' => 25, 'code' => 794, 'name' => 'TAME'],
            ['departament_id' => 26, 'code' => 1, 'name' => 'YOPAL'],
            ['departament_id' => 26, 'code' => 10, 'name' => 'AGUAZUL'],
            ['departament_id' => 26, 'code' => 15, 'name' => 'CHAMEZA'],
            ['departament_id' => 26, 'code' => 125, 'name' => 'HATO COROZAL'],
            ['departament_id' => 26, 'code' => 136, 'name' => 'LA SALINA'],
            ['departament_id' => 26, 'code' => 139, 'name' => 'MANI'],
            ['departament_id' => 26, 'code' => 162, 'name' => 'MONTERREY'],
            ['departament_id' => 26, 'code' => 225, 'name' => 'NUNCHIA'],
            ['departament_id' => 26, 'code' => 230, 'name' => 'OROCUE'],
            ['departament_id' => 26, 'code' => 250, 'name' => 'PAZ DE ARIPORO'],
            ['departament_id' => 26, 'code' => 263, 'name' => 'PORE'],
            ['departament_id' => 26, 'code' => 279, 'name' => 'RECETOR'],
            ['departament_id' => 26, 'code' => 300, 'name' => 'SABANALARGA'],
            ['departament_id' => 26, 'code' => 315, 'name' => 'SACAMA'],
            ['departament_id' => 26, 'code' => 325, 'name' => 'SAN LUIS DE PALENQUE'],
            ['departament_id' => 26, 'code' => 400, 'name' => 'TAMARA'],
            ['departament_id' => 26, 'code' => 410, 'name' => 'TAURAMENA'],
            ['departament_id' => 26, 'code' => 430, 'name' => 'TRINIDAD'],
            ['departament_id' => 26, 'code' => 440, 'name' => 'VILLANUEVA'],
            ['departament_id' => 27, 'code' => 1, 'name' => 'MOCOA'],
            ['departament_id' => 27, 'code' => 219, 'name' => 'COLON'],
            ['departament_id' => 27, 'code' => 320, 'name' => 'ORITO'],
            ['departament_id' => 27, 'code' => 568, 'name' => 'PUERTO ASIS'],
            ['departament_id' => 27, 'code' => 569, 'name' => 'PUERTO CAICEDO'],
            ['departament_id' => 27, 'code' => 571, 'name' => 'PUERTO GUZMAN'],
            ['departament_id' => 27, 'code' => 573, 'name' => 'PUERTO LEGUIZAMO'],
            ['departament_id' => 27, 'code' => 749, 'name' => 'SIBUNDOY'],
            ['departament_id' => 27, 'code' => 755, 'name' => 'SAN FRANCISCO'],
            ['departament_id' => 27, 'code' => 757, 'name' => 'SAN MIGUEL (LA DORADA)'],
            ['departament_id' => 27, 'code' => 760, 'name' => 'SANTIAGO'],
            ['departament_id' => 27, 'code' => 865, 'name' => 'LA HORMIGA (VALLE DEL GUAMUEZ)'],
            ['departament_id' => 27, 'code' => 885, 'name' => 'VILLAGARZON'],
            ['departament_id' => 28, 'code' => 1, 'name' => 'SAN ANDRES'],
            ['departament_id' => 28, 'code' => 564, 'name' => 'PROVIDENCIA'],
            ['departament_id' => 29, 'code' => 1, 'name' => 'LETICIA'],
            ['departament_id' => 29, 'code' => 263, 'name' => 'EL ENCANTO'],
            ['departament_id' => 29, 'code' => 405, 'name' => 'LA CHORRERA'],
            ['departament_id' => 29, 'code' => 407, 'name' => 'LA PEDRERA'],
            ['departament_id' => 29, 'code' => 430, 'name' => 'LA VICTORIA'],
            ['departament_id' => 29, 'code' => 460, 'MIRITI-PARANA'],
            ['departament_id' => 29, 'code' => 530, 'name' => 'PUERTO ALEGRIA'],
            ['departament_id' => 29, 'code' => 536, 'name' => 'PUERTO ARICA'],
            ['departament_id' => 29, 'code' => 540, 'name' => 'PUERTO NARIÑO'],
            ['departament_id' => 29, 'code' => 669, 'name' => 'PUERTO SANTANDER'],
            ['departament_id' => 29, 'code' => 798, 'name' => 'TARAPACA'],
            ['departament_id' => 30, 'code' => 1, 'name' => 'PUERTO INIRIDA'],
            ['departament_id' => 30, 'code' => 343, 'name' => 'BARRANCO MINAS'],
            ['departament_id' => 30, 'code' => 883, 'name' => 'SAN FELIPE'],
            ['departament_id' => 30, 'code' => 884, 'name' => 'PUERTO COLOMBIA'],
            ['departament_id' => 30, 'code' => 885, 'name' => 'LA GUADALUPE'],
            ['departament_id' => 30, 'code' => 886, 'name' => 'CACAHUAL'],
            ['departament_id' => 30, 'code' => 887, 'name' => 'PANA PANA (CAMPO ALEGRE)'],
            ['departament_id' => 30, 'code' => 888, 'name' => 'MORICHAL (MORICHAL NUEVO)'],
            ['departament_id' => 31, 'code' => 1, 'name' => 'SAN JOSE DEL GUAVIARE'],
            ['departament_id' => 31, 'code' => 15, 'name' => 'CALAMAR'],
            ['departament_id' => 31, 'code' => 25, 'name' => 'EL RETORNO'],
            ['departament_id' => 31, 'code' => 200, 'name' => 'MIRAFLORES'],
            ['departament_id' => 32, 'code' => 1, 'name' => 'MITU'],
            ['departament_id' => 32, 'code' => 161, 'name' => 'CARURU'],
            ['departament_id' => 32, 'code' => 511, 'name' => 'PACOA'],
            ['departament_id' => 32, 'code' => 666, 'name' => 'TARAIRA'],
            ['departament_id' => 32, 'code' => 777, 'name' => 'PAPUNAUA (MORICHAL)'],
            ['departament_id' => 32, 'code' => 889, 'name' => 'YAVARATE'],
            ['departament_id' => 33, 'code' => 1, 'name' => 'PUERTO CARREÑO'],
            ['departament_id' => 33, 'code' => 524, 'name' => 'LA PRIMAVERA'],
            ['departament_id' => 33, 'code' => 572, 'name' => 'SANTA RITA'],
            ['departament_id' => 33, 'code' => 666, 'name' => 'SANTA ROSALIA'],
            ['departament_id' => 33, 'code' => 760, 'name' => 'SAN JOSE DE OCUNE'],
            ['departament_id' => 33, 'code' => 773, 'name' => 'CUMARIBO']
        ]);
    }
}
